### ISSUE TITLE
yobit exchange wallet

### ISSUE THREAD

**Issue by abhayo1990** [Gulden/gulden-official#11]
yobit exchange NLG wallet still on maintenance from 3 month.. pls help me to get my coins.. txid- 7612eef0643a6e570707383bbea04a235ae51bb7f73bdc4565ec886975057afa

**Comment by mjmacleod** [comment]
Unfortunately we absolutely nothing to do with yobit, they have added us without our permission and do not respond to any communication from us. 
From our side we are more than happy to assist with any queries they have but as they refuse to make contact with us there is nothing to do.

As the money is in their wallet there is nothing we can do to assist you from our side. All I can suggest is that you put pressure on Yobit themselves to make your money available.

**Comment by mjmacleod** [comment]
Note issue tracker is for technical issues with the software itself - please follow up further via proper support channels, or have yobit contact us if they have technical questions.

**Comment by abhayo1990** [comment]
but yobit support naver ans me properly they only ans. that please wait...
How to put pressure on yobit?
