### ISSUE TITLE
Legacy account not shown in Windows Desktop wallet 2.0.0.1

### ISSUE THREAD

**Issue by guldenlegacy** [Gulden/gulden-official#122]
### Describe the issue
The legacy account is not shown anymore in the latest client.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Install new client (upgrade from 1.6.4.3
2. Open client
3. No more legacy account (total balance does include the Legacy balance)

### Expected behaviour
Left menu with accounts should show Legacy account, so transactions can be made from Legacy account.

### Actual behaviour
Left menu with accounts is missing the Legacy account.

### Screenshots.
![gulden_client_no_legacy_account](https://user-images.githubusercontent.com/40773940/42182631-2effacbe-7e3f-11e8-9c10-0e53f90a99f7.jpg)

### What version of Gulden are you using?
2.0.0.1

### Machine specs:
- OS: Windows 7
- CPU: Intel Core i7
- RAM: 24GB
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

**Comment by mjmacleod** [comment]
Legacy accounts are not created or shown for new wallets, they are only there for old (legacy) wallets, to have a place to store the old (non-HD) addresses that those wallets contained.

**Comment by guldenlegacy** [comment]
Ok thanks.
But I got my funds still in my legacy wallet (wallet.dat).
How can I transfer the funds now to new HD wallet with this new client?

**Comment by mjmacleod** [comment]
Please contact support for assistance; github issue tracker is only for confirmed issues not for front line end user support.
When/If you have worked through support the issue can be elevated here if actually appropraite.

**Comment by mjmacleod** [comment]
We have been able to confirm that there is an issue with the account hiding when upgrading.
This is only a UI level issue, everything is okay with the wallet it just is hiding the account.

**Comment by mjmacleod** [comment]
This will be fixed in the 2.0.0.2 release which will be out within the next day.

**Comment by guldenlegacy** [comment]
Thanks for the update!
So with the next release, I can send the funds from Legacy to HD wallet?

**Comment by mjmacleod** [comment]
Yes that is correct, note (as was recommended when 1.6.0 first came out) it is strongly recommended to -empty- the Legacy account and then stop using it.

HD accounts offer superior safety, are where most users store their money and are protected by your recovery phrase while legacy accounts are not and exist only for backwards support and power users.

**Comment by guldenlegacy** [comment]
Ok thanks.
Yes, it will be the first think I'll do once I can get to my funds on my legacy account :)

**Comment by mjmacleod** [comment]
Note this should now be resolved in latest build - please reopen if not, sorry for the inconvenience.
