### ISSUE TITLE
createrawtransaction not working

### ISSUE THREAD

**Issue by bitbandi** [Gulden/gulden-official#123]
createrawtransaction rpc call crash the app. (daemon and gui too)

rpc command:

    createrawtransaction "[{\"txid\":\"inputtxhex\",\"vout\":1}]" "{\"Gmyaddress\":7}"

app crash log line:

    Gulden: ./primitives/transaction.h:756: void CTxOut::WriteToStream(Stream&, int32_t) const [with Stream = CHashWriter; int32_t = int]: Assertion `output.nType == CTxOutType::ScriptLegacyOutput' failed.

latest appimage on ubuntu xenial

**Comment by mjmacleod** [comment]
Please confirm 2.0.0.1 or 2.0.0.2?

**Comment by bitbandi** [comment]
i downloaded 2.0.0.1 from official website yesterday (Gulden-2.0.0.1-x86_64.AppImage). But it looks like e6c99bb9c78dd6e9a6615397e05eddcef83f7f13 fixed the issue, and 2.0.0.2 is working.
