### ISSUE TITLE
A compiler with support for C++17 language features is required

### ISSUE THREAD

**Issue by crackfoo** [Gulden/gulden-official#124]
Is building possible on Ubuntu 16.04? I get this error

A compiler with support for C++17 language features is required

I've installed gcc7 but still has same error.

Thanks

**Comment by mjmacleod** [comment]
Compiling on 16.04 is possible but the steps are relatively complicated as it requires (amongst other things)  a c++17 compatible compiler.

The cleanest way to compile on 16.04 is to use the gitian-builder script this way you can avoid upgrading the actual base system - I'll post instructions for this in the near future.
Alternatively simply compile on an 18.04 machine and copy the results across.

The other option (which is honestly the best unless you actually require to manually compile yourself for some reason) is to simply download the latest binary https://github.com/Gulden/gulden-official/releases https://github.com/Gulden/gulden-official/releases/download/v2.0.0.2/Gulden-2.0.0.2-x86_64-linux.tar.gz extract it and use the GuldenD from there - without all the fuss of compiling.

As the official binaries are compiled with gitian it is bit for bit identical to what you will get if you compile via the gitian process anyway.

**Comment by AndreyNag** [comment]
Hi. I did as you wrote above. But many errors is in the debug.log
I did as you wrote above.

> 2018-07-19 08:45:07 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)
> 2018-07-19 08:45:07 ERROR: ProcessSyncCheckpoint: ReadBlockFromDisk failed for sync checkpoint 64bf8bf3e6b17cf1cc548b9c4fd51297657f8f3f31683f27d530f028d3da0b1e
> 2018-07-19 08:45:07 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)
> 2018-07-19 08:45:07 ERROR: ProcessSyncCheckpoint: ReadBlockFromDisk failed for sync checkpoint 64bf8bf3e6b17cf1cc548b9c4fd51297657f8f3f31683f27d530f028d3da0b1e
> 2018-07-19 08:45:07 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)
> 2018-07-19 08:45:07 ERROR: ProcessSyncCheckpoint: ReadBlockFromDisk failed for sync checkpoint 64bf8bf3e6b17cf1cc548b9c4fd51297657f8f3f31683f27d530f028d3da0b1e
> 2018-07-19 08:45:07 UpdateTip: new best=64bf8bf3e6b17cf1cc548b9c4fd51297657f8f3f31683f27d530f028d3da0b1e height=777618 version=0x28000000 versionpow2=0x00000000 log2_work=63.454939 tx=1971021 date='2018-07-19 08:45:02' progress=1.000000
> 2018-07-19 08:45:07 ProcessSyncCheckpoint: sync-checkpoint at 64bf8bf3e6b17cf1cc548b9c4fd51297657f8f3f31683f27d530f028d3da0b1e
>

**Comment by mjmacleod** [comment]
Hi, though those are labelled as error they are actually just informational and can be safely ignored, they will appear a lot less frequently in the near future once witnessing activates.

**Comment by AndreyNag** [comment]
I don't think so. I try to mine gulden by 45GH/s in about a day. Miner has find block, but pool is not. There are fatal error or software incompatibility with Ubuntu 16.04LTS in a precompiled module.
Need help to compile daemon by 16.04.
Thnx for attention.

**Comment by mjmacleod** [comment]
If you are facing issues they are certainly -not- related to the above "error" logs which are as I have said purely informational.

In terms of 16.04 your options for now are:
Compile on a newer distro.
Use the precompiled binary - there is really no legitimate reason you need to compile at all and the binaries will work better anyway.
Mine on a different pool for now.
Mine a different coin for now.

We are in the middle of a very complex roll out which activates tomorrow, so while we will add instructions for it in the future; supporting compilation on old distributions (something that isn't actually needed when binaries exist) is extremely low down on the priority list right now and will have to wait.

**Comment by AndreyNag** [comment]
Thank you.
Good luck. 
Will wait new design.

**Comment by tuaris** [comment]
Putting in these drastic changes to build requirements at the same time as doing a hard fork on the network is a very very poorly managed process.

**Comment by mjmacleod** [comment]
A few things:

1) This is not a hard fork, its backwards compatible for everyone except miners, so the only people who -have- to upgrade are miners.If you were actually following properly you would know this is not a hard fork.

2) There are binaries that are perfectly fine, insisting on compiling yourself without the technical skills to do so adequately is a far larger problem than any perceived issue you are claiming with our process.
It is you who has decided that you both need to compile yourself and use an old distribution, the Gulden team never asked you to do any of these things.

3) You understand literally none of the reasoning involved in the decision making process; as is made quite evident by the fact that you don't even know that this is not a hard fork  - so it is extremely rude, arrogant and unprofessional of you to assume that you can make any judgment about why the decisions (that you know nothing about) were made.

4) I'm happy to help with any valid questions people have as time is allowed, this is the place for that. If you have valid issues file a ticket and then wait for assistance. Give information if you think it will help.

5) This is not however a soapbox for you to come and give your 'opinion' so keep that to yourself.


Bug reports - welcome
More information - welcome
Pull requests to improve the process - welcome
Pull requests to improve the documentation of the process - welcome
Comments about your 'opinion' and feelings, not welcome under any circumstances.

**Comment by mjmacleod** [comment]
Build instructions for ubuntu 14 https://gist.github.com/mjmacleod/31ad31386fcb421a7ba04948e83ace76

**Comment by mjmacleod** [comment]
Further to all the other build instructions theres now a very simple to use docker build script in 'developer_tools' subfolder.

`./developer_tools/build_docker.sh`
