### ISSUE TITLE
RPC call getwitnessinfo disabled

### ISSUE THREAD

**Issue by jcgaarden** [Gulden/gulden-official#126]
### Describe the issue

RPC call "getwitnessinfo" gives me this result:
Method not found (disabled)

In de gulden.conf I removes the "disablewallet=1"
After that its ok.

This option should work without wallet

### What version of Gulden are you using?
2.0.0.6

### Machine specs:
- OS: Windows Server 2012

**Comment by mjmacleod** [comment]
This should now be fixed in 2.0.0.11 build
