### ISSUE TITLE
Certain UI elements clipping in Windows 10 when using DPI scaling

### ISSUE THREAD

**Issue by kevinvalk** [Gulden/gulden-official#131]
Probably related to #88.

On Windows 10 you can enable Scale and layout (DPI scaling) to enlarge UI elements.
![image](https://user-images.githubusercontent.com/3524694/43278560-c1be1cdc-910b-11e8-9ee4-7e3a4d458eb1.png)

This scaling does not properly work on the Gulden application as it will start clipping certain UI elements as highlighted in the picture.
![problems](https://user-images.githubusercontent.com/3524694/43278501-961ec996-910b-11e8-93e6-b0287446334f.PNG)

I have found this problem in the following setup:
- Gulden Wallet version 1.6.X - 2.0.0.9
- Windows 10
- Display resolution 1920x1080
- Scale and layout 125%

**Comment by mjmacleod** [comment]
Don't think its directly related to #88 as all users in #88 s far have confirmed standard DPI settings, but will look into it. thanks for the info.

**Comment by mjmacleod** [comment]
Can you please confirm if the latest build fixes this?

It should  avoid the clipping by essentially ''ignoring" the setting. I realise this is not ideal, and ideally we should respect the setting but for now its the lesser of two evils I think until we can dedicate more resources to it.

**Comment by kevinvalk** [comment]
Hi, sadly in version v2.0.0.10-571de315a (64-bit) the issue remain the exact same.

Sorry!

**Comment by mjmacleod** [comment]
Oh thats odd, after getting some more testers to look it seems it happens on some windows machines with those settings but not all of them. I'll try have a closer look soon. thanks.

**Comment by mjmacleod** [comment]
General clean-up of all stale ux related issues, as we are soon moving to a new electron based UI. If issue is urgent and/or still reproduces reopen w ith further info.
