### ISSUE TITLE
Win64 Wallet (2.0.0.10-571de315a) - Increasing memory usage over time

### ISSUE THREAD

**Issue by EyePeaSea** [Gulden/gulden-official#132]
Issue:
After initially opening the wallet, it consumes about 300MB.  Over time the memory (Private Working Set) usage steadily increases.

     Day 1 = 300MB
     Day 2 = 1,000MB
     Day 5 = 3,350MB

Same occurred with 20.0.0.6 - after a couple of weeks, private working set was up to 6,000MB

To Reproduce:
     1. Run Application
     2. Wait

Gulden Version:
     2.0.0.10-571de315a - 64bit

Client machine: 
- OS:  Windows 7 SP1 - Enterprise - 64bit
- CPU: 4 CPU - 2.5Ghz 
- RAM: 8GB
- Disk size: 60GB
- Disk Type: Non-SSD

**Comment by EyePeaSea** [comment]
And after 9 days, it's up to 5,705MB

**Comment by mjmacleod** [comment]
Looking into this soon (relatively high on priority list) just other things were ahead of it, thanks for the report.

**Comment by mjmacleod** [comment]
Still busy looking into it, but if you are willing please trial this build https://drive.google.com/drive/folders/1V5oFp7XORf-vwkcDeOc0gPqp6mOflIx2?usp=sharing and let me know if it has any effect on the issue.

**Comment by EyePeaSea** [comment]
Malcolm,

Let me check the latest release - it's been running a couple of days. If it's showing the same symptoms then I'll try the build on your link.

Regards

Ian

**Comment by EyePeaSea** [comment]
2.0.0.11 was experiencing the same thing.  2.0.0.12 installed - I'll post an update once it's been running for 3 or 4 days.

Ian

**Comment by EyePeaSea** [comment]
Definitely looks better.  Peak Working Set hasn't increased in 24 hours and Work Set is sitting at about 500MB.

**Comment by mjmacleod** [comment]
Okay thanks.

**Comment by mjmacleod** [comment]
Closed in 94ab639983fec168dc5ade90a1ea8d1f73d87382

**Comment by tofra** [comment]
Is this only for the win64 build?

**Comment by mjmacleod** [comment]
Issue affects all desktop (UI) builds but not GuldenD - its just more a bit more noticeable for windows users.
