### ISSUE TITLE
Witness period finished, but not getting reserved funds back

### ISSUE THREAD

**Issue by guldenlegacy** [Gulden/gulden-official#136]
### Describe the issue

I made a witness account and hold funds for 1 month.
The 1 month is over and at the right bottom I clicked the button "Account Legen" (Empty Account).
I get the reward in my main account, but not the entire funds.
I check the witness account again, and it shows it is hold till next year, 365 days.
Is this an error in the wallet and can I still get to my funds somehow?
I didn't click a button or agree with another 365 days of witnessing.

### Can you reliably reproduce the issue?
I guess so.

#### If so, please list the steps to reproduce below:
1. Make witness account and transfer funds to it
2. Set period for 1 month
3. After 1 month, try to empty account and get funds+rewards back

### Expected behaviour
When emptying witness account, the funds and reward should be transferred to my main account

### Actual behaviour
Only the reward is transferred, the funds is somehow hold for another whole year without my permission.

### Screenshots.
![gulden_witnessing_another_year_not_ok](https://user-images.githubusercontent.com/40773940/44514522-a95a5000-a6c0-11e8-92ab-10ecb19f4a57.jpg)

### What version of Gulden are you using?
2.0.0.11

### Machine specs:
- OS: Windows 7

**Comment by mjmacleod** [comment]
Please deal first with https://gulden.com/support for end user issues before opening github issues.

**Comment by mjmacleod** [comment]
One of our support staff has looked into it and your lock period is for 1 year and not 1 month.
You can confirm this also by looking up your address via dactual.com or similar.

The UI for lock period is quite clear so I'm not sure how the confusion may have arisen on your side, please feel free to discuss further with support staff so they can better understand how you reached this situation.
