### ISSUE TITLE
All buttons visible at the same time during sync

### ISSUE THREAD

**Issue by blieb** [Gulden/gulden-official#141]
### Describe the issue
When I started the app after a few days not used, the app started syncing. Then I did go to the witness account. And it looked like it was not yet funded. Also there was a fund and empty button at bottom. It did disappear when I moved to another witness account and back. but then was sync already completed.

### Expected behaviour
show graph and only 1 button

### Actual behaviour
no graph but list of accounts to fund from. and 2 buttons

### What version of Gulden are you using?
2.0.17

### Machine specs:
- OS: MacOS 10.13.6
- CPU: 3,1 GHz Intel Core i5
- RAM: 16 GB 1333 MHz DDR3
- Disk size:1TB
- Disk Type (HD/SDD): hdd

**Comment by robobit** [comment]
So far unable to reproduce. Examined the code-paths in WitnessDialog::doUpdate and there is none that will result in both the fund and empty buttons to be enabled simultaneously. If this still happens please re-open and add more details of how/when this happens.
