### ISSUE TITLE
Gulden Linux 64 bits appimage doesn't do integration with the system

### ISSUE THREAD

**Issue by forest-hermit** [Gulden/gulden-official#147]
Since 2.1.0 the Linux appimage doesn't ask on first run to do integration with system (creating the proper placed link in order it shows up in the apps list).

**Comment by mjmacleod** [comment]
It appears that the AppImage team have deprecated this functionality.
Users should install 'appimaged' or 'AppImageLauncher' on their systems; if you are on a distro where this is not installed by default consider filing or posting on a distro bug and requesting it be made a default app.
