### ISSUE TITLE
iOS app crash on transaction screen (when nocks offline?)

### ISSUE THREAD

**Issue by blieb** [Gulden/gulden-official#153]
The latest version of the iOS app crashed last night on the transaction screen. This issue was also confirmed by one other user. 

At the moment of crash nocks was down for maintenance so I think this is the issue.

#### If so, please list the steps to reproduce below:
1. Shut down nocks
2. open app
3. go to transactions and wait a sec. 

### Expected behaviour
You should see a list of transaction

### Actual behaviour
the app crashes.

### What version of Gulden are you using?
1.8.1 (64)

### Machine specs:
- OS: iOS 12.1.3
- iPhone 7

**Comment by rplasman** [comment]
Possibly fixed in latest builds

**Comment by mjmacleod** [comment]
Closing issue, please reopen if issue persists.
