### ISSUE TITLE
Clicking to pay on desktop wallet not working correctly

### ISSUE THREAD

**Issue by RobStof** [Gulden/gulden-official#159]
### Describe the issue

I have one question about the Gulden desktop wallet. Whenever I try to click the donate to GeenStijl wallet link (on their webpage) it doesn't correctly copy it into the Gulden wallet. So each time I have to click and copy and paste the adress. Works perfectly fine on android through. Greetings!

**Comment by robobit** [comment]
Fixed by f7f7b8c089126e5c977606d72abe2a716aa244c5
