### ISSUE TITLE
Witness expected rewards on desktop wallet not correct

### ISSUE THREAD

**Issue by RobStof** [Gulden/gulden-official#160]
### Describe the issue
Hi Malcolm,
Could you please remove the 'safety/protection' of the expected witness earnings graph? Because it's a bit misleading (it shows lower than it actually is) and when you select the ammount, it says you will earn more if you put more than like 300k Guldens in Witness for 3 years. While the actual ammount is around 200k for best profit. (See Aat's graph: https://docs.google.com/document/d/1QYiUvBPkuNmwUJ9nYJ_b6kAHfqBcmCdUaguChjbg2Cw/edit )

**Comment by RobStof** [comment]
On page 7 (the actual now)

**Comment by mjmacleod** [comment]
I think there is maybe a bit of a misunderstanding at play here based on two different ways to look at things.

The app is looking at things from the perspective of "I have x amount of Gulden I want to invest" how do I earn the most gulden with them.

While some users are looking from the perspective of "What amount of Gulden do I need to put in a witness account to make the best percentage earnings"

There are unfortunately some subtle differences between these two views that are difficult to reconcile.

To use your example, of 300k gulden and to work on the graph aat has presented:
If I have 300k gulden I am looking to invest in witnessing I can place these 300k gulden in a single witness account for 3 years and (assuming network stays the same) expect around 7.8% earnings on it (23700 yearly).
Or I can put 200k gulden in one 3y account and get 8% earnings (true this is higher percentage wise - 16000 yearly) but the other 100k must then go in a separate account where it earns at only 7.5% (7500 yearly) - in total this 300k earns 23500 yearly, or slightly less than the 300k.
IF the network weight increases over the time period the gap in performance between the single large account and the smaller accounts will further widen (making the single account win by a larger margin)
IF the network weight shrinks (after phase 4 only) the larger account has the benefit of being able to 'split' into smaller accounts and recombine at a later date if the network weight raises again - which the smaller accounts cannot do.

In terms of this way of thinking (I want to invest x gulden in witnessing) - a single larger account will always outperform a smaller account, and this is what the UI attempts to encourage.
There is a single exception - where a single account is bad, and this is where its weight is so large that it exceeds the maximum weight, at this point it can (not always) be better to have two accounts - and for this reason there is currently a warning.
After phase 4 when the above mentioned "splitting" functionality kicks in this warning will be removed as it will no longer be necessary - it will always be best to just make a larger account at this point.

From the (I want to invest the optimal amount of gulden to get the best percentage) way of thinking it is a bit different - I'm not sure I want to really encourage this way of thinking (given that network weight is subject to change over a long period of time anyway and therefore the amount that earns optimal percentage is subject to fluctuation).
However for this style of thinking it is true that a smaller amount sometimes does better in terms of percentages.

**Comment by RobStof** [comment]
Ok thank you for your explanation. I also heard that the desktop version (and when we click on any witness account) won't take as much time to load as now is the case, with the coming of Unity. Thanks and case can be closed.
