### ISSUE TITLE
v2.1.0.5 runtime error when starting up Gulden(QT) after the first time

### ISSUE THREAD

**Issue by NoAgendaIT** [Gulden/gulden-official#166]
This is a Funtoo Linux machine, x64, with gcc 7.4.1, glibc 2.27.

I have pulled Gulden from the github repository, checked out tag v2.1.0.5, and I have followed the build instructions and checked the dependencies that are appropriate for this distribution.

The compilation succeeded and running it for the first time works - a wallet is generated and the blockchain synchronizes.

However, when I quit and then restart Gulden, the issue is as follows:

```
Gulden: ../../src/key.cpp:307: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
[1]    11264 abort      src/qt/Gulden
```

Running it with strace:

```
readlink("/etc/ssl/certs/DST_Root_CA_X3.pem", "../../../usr/share/ca-certificat"..., 4095) = 61
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=200, ...}) = 0
lstat("/usr/share", {st_mode=S_IFDIR|0755, st_size=4494, ...}) = 0
lstat("/usr/share/ca-certificates", {st_mode=S_IFDIR|0755, st_size=14, ...}) = 0
lstat("/usr/share/ca-certificates/mozilla", {st_mode=S_IFDIR|0755, st_size=8324, ...}) = 0
lstat("/usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt", {st_mode=S_IFREG|0644, st_size=1200, ...}) = 0
stat("/etc/ssl/certs/DigiCert_Assured_ID_Root_CA.pem", {st_mode=S_IFREG|0644, st_size=1350, ...}) = 0
lstat("/etc", {st_mode=S_IFDIR|0755, st_size=5200, ...}) = 0
lstat("/etc/ssl", {st_mode=S_IFDIR|0755, st_size=68, ...}) = 0
Gulden: ../../src/key.cpp:307: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
lstat("/etc/ssl/certs", {st_mode=S_IFDIR|0755, st_size=11610, ...}) = 0
+++ killed by SIGABRT +++
[1]    19912 abort      strace src/qt/Gulden
```

**Comment by mjmacleod** [comment]
hmm, a bit strange, I'm not sure whether that assert is the actual problem or if its just a knock on effect of something going wrong earlier in the load.
Does it still occur if you launch with e.g. './src/qt/Gulden -disablewallet'?

Some additional info that might be handy:
1) Output of 'ldd src/qt/Gulden'
2) Copy of 'debug.log' after starting with './src/qt/Gulden -debug=1' and allowing the problem to occur  (You can create a new temporary directory and also pass -datadir=/path/to/dir' to avoid sending any data from original wallet)

**Comment by NoAgendaIT** [comment]
The output from `ldd`:

```
	linux-vdso.so.1 (0x00007ffe7dd5a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f68a2071000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f68a1e69000)
	libdouble-conversion.so.1 => /usr/lib64/libdouble-conversion.so.1 (0x00007f68a1c5d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f68a1a59000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f68a16cf000)
	libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f68a148c000)
	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f68a125a000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f68a0fa0000)
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f68a0d9e000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f68a0a60000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f68a0836000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1/libstdc++.so.6 (0x00007f68a04ab000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1/libgcc_s.so.1 (0x00007f68a0294000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f689fecc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68a4ebb000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f689fcc5000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f689fab5000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f689f87f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f689f668000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f689f464000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f689f25e000)
	libbsd.so.0 => /usr/lib64/libbsd.so.0 (0x00007f689f047000)
```

The debug log contains nothing of interest - Here's the last part with `-debug=1 -verbose=1 -printtoconsole=1`:

```
2019-06-02 17:52:17 UpdateTip: new best=b17d581ad610afeaae4e857bc7a015e5a1b6d46e36f31d5e4f09298c68e81e90 height=94983 version=0x00000002 versionpow2=0x00000000 log2_work=52.139783 tx=312916 date='2014-08-06 11:52:06' progress=0.103032 cache=0.0MiB(222txo)
2019-06-02 17:52:17   - Connect postprocess: 0.14ms [0.00s]
2019-06-02 17:52:17 - Connect block: 0.51ms [0.01s]
2019-06-02 17:52:17   - Load block from disk: 0.02ms [0.00s]
2019-06-02 17:52:17     - Sanity checks: 0.02ms [0.00s]
2019-06-02 17:52:17     - Fork checks: 0.04ms [0.00s]
2019-06-02 17:52:17       - Connect 3 transactions: 0.05ms (0.017ms/tx, 0.025ms/txin) [0.00s]
2019-06-02 17:52:17     - Verify 2 txins: 0.07ms (0.035ms/txin) [0.00s]
2019-06-02 17:52:17     - Index writing: 0.04ms [0.00s]
2019-06-02 17:52:17     - Callbacks: 0.02ms [0.00s]
2019-06-02 17:52:17   - Connect total: 0.25ms [0.01s]
2019-06-02 17:52:17   - Flush: 0.02ms [0.00s]
Gulden: ../../src/key.cpp:307: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
2019-06-02 17:52:17   - Writing chainstate: 0.02ms [0.00s]
[1]    17874 abort      src/qt/Gulden -verbose=1 -debug=1 -printtoconsole=1
```

**Comment by mjmacleod** [comment]
Thanks, I would have preferred the whole log as even if it might appear to contain nothing of interest to you there might be some small clues I can glean from it with my knowledge of the project.

Anyway...

ECC_Start should be called only once, very early in program creation, I can't see any obvious route via which it could be getting called twice (which is necessary for this assert to trigger).

There exist two main possibilities:
1) It is somehow getting called twice legitimately, this is unlikely, but would trigger the assert if it did occur.
2) Some kind of memory corruption (from some other issue) is landing us here, its probably not related to libraries if it doesn't happen on first run of the program...

Can you paste your config.log?
Further I'd recommend trying to configure with --enable-debug and see if the same thing happens with a debug build.

**Comment by NoAgendaIT** [comment]
Alright. I did a `make clean` followed by appending --enable-debug to ../configure. The debug.log doesn't contain anything new but here is it anyway. The error goes straight into the console and hasn't changed either. config.log is also attached.

[debug.log](https://github.com/Gulden/gulden-official/files/3245156/debug.log)
[config.log](https://github.com/Gulden/gulden-official/files/3245157/config.log)

**Comment by mjmacleod** [comment]
One possible thing I've picked up is that it is setting additional CXXFLAGS for some reason; ac_cv_env_CXXFLAGS_value='-march=native -O3 -pipe'

I'm not sure if you have CXXFLAGS and CFLAGS set on your 'env'?
While in theory these flags should be fine there exists the possibility that they might be introducing issues, it might be a good idea to unset these and then do a clean configure and build and see if it helps.

Assuming building without these flags does not help the next step would probably be to run the debug build in gdb and paste the backtrace when it exits.

**Comment by NoAgendaIT** [comment]
Alright. Well even without the CXXFLAGS/CFLAGS, the same things happens.

Let's run it in gdb - I have installed it but not used it before so could you tell me what to do?

**Comment by mjmacleod** [comment]
You should simply be able to do 'gdb ./src/qt/Gulden.exe'

And then once inside gdb just type 'run' to run it or 'run -debug=1' or similar if you need to pass arguments to the program.

Once it crashes it should hopefully print some information, you can also then type "thread apply all bt" which should provide more information.

**Comment by NoAgendaIT** [comment]
Alright. I'll just attach the entire output. Thanks for your patience @mjmacleod.
[gdb.txt](https://github.com/Gulden/gulden-official/files/3247992/gdb.txt)

**Comment by mjmacleod** [comment]
Sorry still don't have a conclusive answer for you, thanks for your cooperation so far - would really like to get to the bottom of whatever is going on.

Some more flags you can add to try remove a few more variables here (If the problem remains then at least we know that these aren't responsible - and if it goes away then we know that they are):
'-rootcertificates="" -listenonion=false'

**Comment by NoAgendaIT** [comment]
That goes to a segfault immediately. Interesting.

Here's the bt from thread 1:

```
Starting program: /docs/markvd/src/gulden-official/build/src/qt/Gulden -debug=1 -verbose=1 -rootcertificates='' -listenonion=false
(...)
Thread 1 (Thread 0x7ffff7e0bbc0 (LWP 24021)):
#0  0x00007ffff34d36da in ?? () from /lib64/libc.so.6
#1  0x00007ffff54a23bc in ?? () from /usr/lib64/libcrypto.so.1.0.0
#2  0x00007ffff54a271e in lh_insert () from /usr/lib64/libcrypto.so.1.0.0
#3  0x00007ffff53f5d4b in OBJ_NAME_add () from /usr/lib64/libcrypto.so.1.0.0
#4  0x00007ffff7e7cb6b in ?? () from /usr/lib64/libssl.so.1.1
#5  0x00007ffff7bc6467 in __pthread_once_slow () from /lib64/libpthread.so.0
#6  0x00007ffff28c2509 in CRYPTO_THREAD_run_once () from /usr/lib64/libcrypto.so.1.1
#7  0x00007ffff7e7cd67 in OPENSSL_init_ssl () from /usr/lib64/libssl.so.1.1
#8  0x00007ffff78c89dc in ?? () from /usr/lib64/libQt5Network.so.5
#9  0x00007ffff78c2439 in ?? () from /usr/lib64/libQt5Network.so.5
#10 0x00007ffff78aa1c4 in ?? () from /usr/lib64/libQt5Network.so.5
#11 0x00007ffff789ffbd in QSslConfiguration::defaultConfiguration() () from /usr/lib64/libQt5Network.so.5
#12 0x00005555555e9f18 in main (argc=5, argv=0x7fffffffd9d8) at ../../src/qt/gulden.cpp:608
```

**Comment by mjmacleod** [comment]
I've just noticed after inspecting the various gdb outputs again that it looks like your build is using the system qt and not the qt from the depends directory.

In theory this is fine, but if its ending up with headers from the one and libs from the other, or some other similar but more subtle confusion then this might explain things.

It is probably better to avoid mixing the two.
My suggestion is to start with a clean repo and to not build the depends dir at all, but instead simply emerge all required dependencies via the system package manager and then go straight on to running configure against the system library versions.

I suspect this should clear the issue up but if it doesn't it will at least eliminate a bunch of possibilities.

**Comment by NoAgendaIT** [comment]
Well that's odd - I expected it to fix the issue, but it still happens! Something's real iffy...

So what I did was re-clone the repo and check out the tag, autogen; mkdir build; cd build; ../configure (without the --prefix=../depend...), make. And it still happens!

I'm starting to suspect that this is related to something being wrong on my system... what say you?

**Comment by mjmacleod** [comment]
I'm hesitant to blame your system when there is quite possibly something in the code (or build system) at play that just happens to be triggered by the unique circumstances on your box.
Especially since you (I assume?) have other programs running that don't present such issues.

If it is our code at fault - then I of course want to fix that.

However that said I do all my development on gentoo, which is of course very similar to funtoo, I have the same library versions as you installed and I am unable to reproduce (and have never seen) this issue. We also have zero reports (that I know of) with the official binaries.

I do run my gentoo on very conservative cflags these days (basically just -O2 -pipe) so it could be that your cflags are causing something unexpected somewhere in one of the libraries used. Or it could be something else entirely. (What filesystem are you running anything unusual?)

I'm happy to keep digging if any more usable information crops up, but at this point I'm low on ideas.

On any other distro we could try run it in valgrind (for example) and see if any memory corruption turns up - but I think valgrind doesn't work on 64 bit funtoo systems that use '-march' (due to unsupported instructions in the binary)

**Comment by NoAgendaIT** [comment]
I have compiled it without the CFLAGS, and debug enabled, which enables -O0 (and no -march)

I also confirmed that my disks aren't full, and I moved the storage from btrfs to zfs and recompiled. Could still be file corruption on my root FS - one never knows for sure. But the fscks return 0.

And I made sure that ccache isn't using stale info (I set CCACHE_RECACHE=1 to force it to recompile&recache, it's the better alternative to not using ccache at all)

I have a 810MB tar.xz file for you, https://voidzero.net/tmp/gulden-official2.1.0.5-voidzero.tar.xz

**Comment by mjmacleod** [comment]
Does running './src/GuldenD' also crash or does that run smoothly?

**Comment by mjmacleod** [comment]
Something I've noticed from the tarball is that your Gulden binary is looking 'libcrypto1.1' and 'libssl1.1' - I don't think its ever been tested explicitely with these.

**Comment by NoAgendaIT** [comment]
Oh that's possible - because I compiled against system. I can compile against the dependencies from the depends directory and send you that tarball if you'd like.

./src/GuldenD runs well. It's only the QT application giving me a headache. I also tested it on my other machine but same story there.

**Comment by mjmacleod** [comment]
"I can compile against the dependencies from the depends directory and send you that tarball if you'd like." - worth a try

**Comment by mjmacleod** [comment]
Closing du e to inactivity, reopen if still relevant
