### ISSUE TITLE
Installer software can not handle diacritical characters in the data path

### ISSUE THREAD

**Issue by aat58** [Gulden/gulden-official#169]
If in the datapath for example an "**é**" is used the installer or wallet software crashes 
The issue is detected now at two clients with the name René and is consistent
Both clients wanted to update from 2.1.0.5 to 2.1.0.6
In earlier updates there wasn't a problem

1. Take a datapath with an é for example c:\users\rené\appdata\roaming\gulden
2. an existing wallet is for example version 2..1.0.5
3. Download and install the 2.1.0.6 software (windows 64bit)
3. The install wil crash
This is a screenshot of client René Bakker
https://gyazo.com/242447e5109005de8f4edf479e311978 and https://gyazo.com/4b5e5f526f0633a15b837b1bd9a954dc

And this is client René Miltenburg
https://gyazo.com/242447e5109005de8f4edf479e311978

- OS: Windows 10 home
- CPU: intel corei5 6200
- RAM: 8Gb
- Disk size:
- Disk Type HD

**Comment by mjmacleod** [comment]
Should be fixed by 2.1.0.7 release
