### ISSUE TITLE
Core dump for 2.1.0.7

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#171]
### Describe the issue
Application failed during starting up.

### Can you reliably reproduce the issue?
no

#### If so, please list the steps to reproduce below:
1. run the application
2. application failed during startup
3. command line reported

    Gulden: key.cpp:307: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.                            
    Aborted (core dumped) 

Starting application again did not result in this error.

Note, application was forcefully closed (by choosing close in the window decoration because the gui was stuck) in the run before the run that the error occured.

### What version of Gulden are you using?
2.1.0.7

### Machine specs:
- OS: Ubuntu 19.04 up to date

**Comment by mjmacleod** [comment]
possibly related #166

**Comment by mjmacleod** [comment]
Closing due to massive codebase changes. reopen if similar occurs in 2.2 release series
