### ISSUE TITLE
getblocktemplate - Method not found

### ISSUE THREAD

**Issue by crackfoo** [Gulden/gulden-official#173]
gulden-cli getblocktemplate
error code: -32601
error message:
Method not found

gulden-cli getinfo
{
  "version": 2010011,
  "protocolversion": 70016,
  "walletversion": 60000,

Any ideas why not gbt????

Downloaded the binaries....

**Comment by mjmacleod** [comment]
Hello, yes, see the following:
https://medium.com/@MacLeod_MJ_za/an-introduction-to-sigma-the-new-cpu-friendly-algorithm-for-gulden-9395b2db9357
https://medium.com/@Gulden/sigma-is-here-c33724e6de5d

As of the 16th Gulden will no longer be Scrypt but will use our new CPU algorithm SIGMA to replace it, as a CPU algorithm there is no real need for pools and therefore no point in the developers wasting time maintaining GBT.

While we can't stop people from creating mining pools for SIGMA should they wish it is up to them to implement that and not something we plan to support.

Until SIGMA activates on the 16th Scrypt pools can continue to mine using versions prior to 2.1.0.11

**Comment by crackfoo** [comment]
okie
