### ISSUE TITLE
Errors building on armv7l

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#179]
As with [Dash](https://github.com/dashpay/dash/issues/2562), I am trying to build Gulden on armv7l (note: last character is the letter L) as found in https://www.turris.cz/en/omnia/. Reason is that the pre-build binaries do not work on this device. The system is Ubuntu 19.04 with gcc 8. When following documentation, I deed to do this extra:

    sudo apt-get install libboost-thread-dev libcrypto++-dev

The commands are:

    ./autogen.sh
    cd depends
    make NO_QT=1 NO_UPNP=1
    cd ..
    mkdir build && cd build
    ../configure --prefix=$PWD/depends/armv7l-unknown-linux-gnueabihf --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
    make -j

and make results in these errors:

    ...
      CXX      bench/bench_sigma-bench_sigma.o
      AR       crypto/libgulden_crypto_sse3.a
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    make[2]: *** [Makefile:9199: libgulden_wallet_a-account.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    ...
    make[2]: *** [Makefile:12776: wallet/test/test_test_gulden-accounting_tests.o] Error 1
    In file included from /usr/include/c++/8/vector:69,
                     from ../../src/leveldb/db/version_edit.h:10,
                     from ../../src/leveldb/db/version_edit.cc:5:
    /usr/include/c++/8/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {std::pair<int, leveldb::FileMetaData>}; _Tp = std::pair<int, leveldb::FileMetaData>; _Alloc = std::allocator<std::pair<int, leveldb::FileMetaData> >]’:
    /usr/include/c++/8/bits/vector.tcc:413:7: note: parameter passing for argument of type ‘std::vector<std::pair<int, leveldb::FileMetaData> >::iterator’ {aka ‘__gnu_cxx::__normal_iterator<std::pair<int, leveldb::FileMetaData>*, std::vector<std::pair<int, leveldb::FileMetaData> > >’} changed in GCC 7.1
           vector<_Tp, _Alloc>::
           ^~~~~~~~~~~~~~~~~~~
    g++: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    ...
    make[2]: Leaving directory '/root/a/gulden-official-2.1.0.17/build/src'
    make[1]: *** [Makefile:12950: all-recursive] Error 1
    make[1]: Leaving directory '/root/a/gulden-official-2.1.0.17/build/src'
    make: *** [Makefile:778: all-recursive] Error 1

**Comment by PanderMusubi** [comment]
Currently stuck at:

      CXX      wallet/Gulden/libgulden_wallet_a-guldenwallet.o
      CXX      wallet/libgulden_wallet_a-crypter.o
    ../../src/wallet/crypter.cpp: In member function ‘bool CCrypter::Encrypt(const CKeyingMaterial&, std::vector<unsigned char>&) const’:
    ../../src/wallet/crypter.cpp:98:128: error: expected type-specifier
       98 |         CryptoPP::ArraySource s(&vchPlaintext[0], vchPlaintext.size(), true, new CryptoPP::StreamTransformationFilter(enc, new CryptoPP::VectorSink(vchCiphertext)));
          |                                                                                                                                ^~~~~~~~
    ../../src/wallet/crypter.cpp: In member function ‘bool CCrypter::Decrypt(const std::vector<unsigned char>&, CKeyingMaterial&) const’:
    ../../src/wallet/crypter.cpp:125:23: error: ‘VectorSource’ is not a member of ‘CryptoPP’
      125 |             CryptoPP::VectorSource s(vchCiphertext, true, new     CryptoPP::StreamTransformationFilter(dec, sink));
          |                       ^~~~~~~~~~~~
    make[2]: *** [Makefile:9242: wallet/libgulden_wallet_a-crypter.o] Error 1
    make[2]: Leaving directory '/root/gulden-official-2.1.0.18/build/src'
    make[1]: *** [Makefile:12951: all-recursive] Error 1
    make[1]: Leaving directory '/root/gulden-official-2.1.0.18/build/src'
    make: *** [Makefile:778: all-recursive] Error 1

while having installed

    ii  libcrypto++-dev                        5.6.4-9                           armhf        General purpose cryptographic library - C++ development
    ii  libcrypto++6                           5.6.4-9                           armhf        General purpose cryptographic library - shared library

**Comment by mjmacleod** [comment]
Cryptopp 6 is too old, we are on cryptopp 8.2.0.

Either build and use the depends from the builds folder, or ensure your dependency versions match  or exceed those in the various depends/packages/*.mk

**Comment by PanderMusubi** [comment]
These

    sudo apt-get install libboost-thread-dev libcrypto++-dev

are not needed. Indeed depend downloads all that is needed. I used those packages in order to fix some missing dev files and libs (as you will see below), but better to not have boost and crypt dev file all together. Removed all the crypt and boost dev lib packages from this system.

Now stuck at

    ../configure --prefix=$PWD/depends/armv7l-unknown-linux-gnueabihf
    ...
    configure: error: No working boost sleep implementation found.

Also stuck with

    ../configure --prefix=$PWD/depends/armv7l-unknown-linux-gnueabihf --with-boost-libdir=$PWP/depends/armv7l-unknown-linux-gnueabihf
    ...
    configure: error: --with-boost-libdir expected directory name

(also when added /lib at the end of that command)

**Comment by mjmacleod** [comment]
Please paste entire config.log for configure errors, that way its possible to get an idea of whats actually going on.

**Comment by mjmacleod** [comment]
Note you have a typo in the second version you have `PWP` which should be `PWD`

**Comment by PanderMusubi** [comment]
Thanks, however same result. Now complete output, see https://pastebin.com/raw/zCqj3anh

**Comment by mjmacleod** [comment]
From the config.log 'configure: error: --with-boost-libdir expected directory name' 

This reveals the real problem which is that you are not placing backticks (`) [NB! not inverted commas (')] around '$PWD' and therefore feeding it an incorrect directory name - this also explains why you were having an issue with --prefix.

It should be enough merely to use --prefix and to ensure ($PWD) or (pwd) is enclosed in backticks for shell expansion.

**Comment by mjmacleod** [comment]
Closing as I believe that if done properly with backticks the build will run fine. Should you continue to encounter issues please reopen with an updated config.log
