### ISSUE TITLE
fatal error crash while trying a second transaction from mining adress

### ISSUE THREAD

**Issue by RobStof** [Gulden/gulden-official#181]
### Describe the issue
fatal error crash while trying a second transaction from mining adress (in the same, or not the same block).

### Can you reliably reproduce the issue?
Yes, each time I try to send a transaction after the first one. 

#### If so, please list the steps to reproduce below:
1. Sending 1 G from my mining account to someones account, confirming, no problems. 
2. Sending another 1 G from my mining account to someone elses account, confirming with code, error popup. 
3. Getting fatal error. 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![fatalerror](https://user-images.githubusercontent.com/49819954/67631947-4e605200-f89d-11e9-9ee6-1c9294e7ae4b.jpg)

### What version of Gulden are you using?
latest .18 build (but problem was also present with the first sigma builds)

### Machine specs:
- OS: win10 home
- CPU: i7 intel 7700HQ (kaby lake)
- RAM: 16gb ddr4
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

Extra information:
- Stopping the mining process doesn't make any difference with the fatal error popping up. 
- Tried to wait for the second transaction to find place in a new block, doesn't fix the error. 
- The problem was also present in other sigma builds (I tried several times with the new builds).

**Comment by mjmacleod** [comment]
Fixed in .19 release later today, please reopen if you can reproduce on .19
