### ISSUE TITLE
Unnamed folder in MacOS release

### ISSUE THREAD

**Issue by BramVanBerkel** [Gulden/gulden-official#185]
When untarring the MacOS release, an empty folder (or file, idk) is included in the tar.gz. This is no problem then using `tar -xvf`. But when using PHP's PharData to extract it, it crashes with a `Cannot extract "."`.

This is confirmed when untarring the Linux release. There is no unnamed folder in that tar, and thus PHP doesn't crash when untarring.

### Screenshots.
<img width="756" alt="Screenshot 2019-12-01 at 17 47 44" src="https://user-images.githubusercontent.com/15030624/70218935-3dc8b480-1744-11ea-8f7e-39ebe6420691.png">
<img width="756" alt="Screenshot 2019-12-01 at 17 48 11" src="https://user-images.githubusercontent.com/15030624/70218936-3dc8b480-1744-11ea-982c-cbdf6099e51c.png">

### What version of Gulden are you using?
2.1.0.22

**Comment by BramVanBerkel** [comment]
Hi, is there any status update? Is there more information needed or a testcase? I'll be glad to help!

**Comment by mjmacleod** [comment]
I haven't really had time to look into this yet.

The build system effectively executes this command on a macos machine `tar -zcvf foo.zip -C /tmp/bar/ .` after code signing the executables, where `/tmp/bar` is a folder containing everything thats in the .tar.gz now.

This is almost identical to the command that is run on a linux machine for the linux tarballs (which you say don't have the same isse)

If perhaps you could play around with different `tar` parameters on macos your side and let me know which ones work to create a tarball that does not give you problems - then I'd be happy to modify the build server to use the updated command and solve the issue.

**Comment by mjmacleod** [comment]
This will be fixed as of next release (2.4.1); I've changed to use `--transform` option of `tar` instead of `-C` option which prevents this issue, please comment and reopen if this occurs on any releases from 2.4.1 onwards
