### ISSUE TITLE
Core dump 2.1.0.22

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#186]
Closing down 2.1.0.22 on latest stable and up to date Ubuntu resulted in

    Gulden: /home/ubuntu/build/Gulden/depends/x86_64-linux-gnu/share/../include/boost/thread/pthread/recursive_mutex.hpp:119: bool boost::recursive_mutex::try_lock(): Assertion `!res || res==16' failed.
Aborted (core dumped)

Problem is that I do not have `/home/ubuntu/`, this path should not be used in the build at all.

**Comment by PanderMusubi** [comment]
This does not happen when normally starting and stopping the wallet. It happened after withdrawing earnings from a witness account and from reactivating another witness account.

**Comment by mjmacleod** [comment]
Closing due to massive codebase changes. reopen if similar occurs in 2.2 release series
