### ISSUE TITLE
resetdatadirfull and resetdatadirpartial fail on Windows

### ISSUE THREAD

**Issue by FornaxNLG** [Gulden/gulden-official#189]
Both resetdatadirfull and resetdatadirpartial fail when typed into the Debug console in the GUI-wallet on Windows.

Expected behaviour is they remove all or part of the local copy of the blockchain from the datadir.
Instead they fail on file permissions and actually don't touch any file at all.

Win64 wallet version 2.1.0.22

**Comment by mjmacleod** [comment]
Should be functional in 2.1.0.24 - though it can be a bit slow to close, will see if we can speed up the closing in future.
