### ISSUE TITLE
Application crashes when generate command used in console

### ISSUE THREAD

**Issue by tatdig** [Gulden/gulden-official#191]
### Describe the issue
Application crashes when "generate" or "generatetoaddress" command used in console

#### If so, please list the steps to reproduce below:
1. Open debug window console issue command "generate 11" or "generatetoaddress"
2. Exception raised 

![New Bitmap Image (2)](https://user-images.githubusercontent.com/32492514/72484570-a8085680-37d2-11ea-8c09-59bf0eeae233.png)

### Expected behaviour
Attempt to generate blocks without exception raised

### Actual behaviour
Exception occurs 

### Screenshots.
![New Bitmap Image (2)](https://user-images.githubusercontent.com/32492514/72484570-a8085680-37d2-11ea-8c09-59bf0eeae233.png)

### What version of Gulden are you using?
Latest
### Machine specs:
- OS: Windows 10
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Comment by mjmacleod** [comment]
Will look into it, however what is your use case, are you trying to mine?

Both of these commands are for internal unit tests basically and not intended for actual mining. If you are trying to mine you should be using `setgenerate` and potentially `setminingrewardaddress` - ask for help with these on slack if you don't understand how they work from the rpc help.
