### ISSUE TITLE
Blockchain explorer problems

### ISSUE THREAD

**Issue by GuldenPromotion** [Gulden/gulden-official#192]
The Blockchain explorer on the official site gulden.com does not work properly so also the API can't be used as intended.

1.Go to https://blockchain.gulden.com/status
2.Error!
Can't connect to guldencoind to get live updates from the p2p network. (Tried connecting to guldencoind at 172.17.0.1:9231 and failed.)

Gulden addresses are not up to date and do not show the actual balance.

### Screenshot.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![screenshot](https://user-images.githubusercontent.com/45710313/72788416-3006ba00-3c32-11ea-9759-e6f32179d0d5.png)

**Comment by mjmacleod** [comment]
I've passed the message on and it should be back up.

Note this github/issue tracker is only really for the Gulden software itself (Gulden/GuldenD/ios/android) and not really for surrounding infrastructure. It would be preferable to go through other support channels if possible for this sort of issue. Thanks.

**Comment by GuldenPromotion** [comment]
Thank you Malcolm! I have tried to report it otherwise but it keeps on going down after a while. Have a nice day
