### ISSUE TITLE
Feature request: Reset miningstats when changing parameters

### ISSUE THREAD

**Issue by FornaxNLG** [Gulden/gulden-official#193]
The wallet keeps track of the Best Reported h/s when mining. After changing the mining parameters the wallet currently sticks to the best number it has seen since it started, even when the new parameters result in a lower hashrate (like mining with less threads or a smaller arena).

A way to reset the stats would be nice to have. Possibly via f.e. a new RPC-command like `resetminingstats` or an automatic reset after the use of `setgenerate`  

Walletversion: Desktopwallets 2.1.0.24 and earlier.

**Comment by mjmacleod** [comment]
As of next build every fresh run of the mining loop should reset the statistics
