### ISSUE TITLE
The new 2.2.0 version breaks the wallet.dat

### ISSUE THREAD

**Issue by cdarken** [Gulden/gulden-official#201]
### Describe the issue

Version 2.2.0 broke my wallet. The mining address changed and it also altered my seed phrase.
The balance seems to be correct in the wallet, but if I look for the new address in the explorer it can't be found.

#### If so, please list the steps to reproduce below:
1. recover wallet
2. create the mining account (the address is the same with the one from version 2.1.0.24 but the balance is zero)
3. rescan the wallet. this has the result that the balance appears but the mining address and the seed change

**Comment by mjmacleod** [comment]
In what way does the seed 'change' - are the words actually different or are you talking about it having a number at the end?

**Comment by cdarken** [comment]
Yes, it has a number appended at the end.

**Comment by mjmacleod** [comment]
Okay, this is actually a new feature the number at the end uses a special compact encoding to encode a birthdate that when present enables faster recovery in future.
It doesn't impact the recovery phrase in any way, and won't cause any issues.

I'm not sure why you have a new mining address, as that shouldn't happen and doesn't happen on a test wallet here - do you not maybe have more than one mining account and they are getting confused?

The new address would not appear on the explorer as you haven't mined into it yet, the explorer cannot know about unused addresses only used ones.

**Comment by cdarken** [comment]
It's the same account but the address changes after rescan, as I said. Should I try to recover the wallet with the appended number?

**Comment by mjmacleod** [comment]
I can now reproduce the address change (it happens only on a wallet upgrade)

Note this isn't harmful in any way, other than being annoying in terms of the address being different - if you want the original address recovering with the appended number will probably put you in a state where you are back on it.

**Comment by cdarken** [comment]
I recovered from the modified seed. But the wallet still needs rescan as the balance is initially zero. After rescan it changes again. But if it's not an issue, that's ok.

**Comment by mjmacleod** [comment]
Is your mining address now as before?

**Comment by mjmacleod** [comment]
Okay the change is a bit weird, as it shouldn't do that, but it shouldn't be an issue either (other than messing up your statistics if you wanted all mining to be on one address)

If you are concerned you can just do `validateaddress address` in debug console to ensure it is part of your wallet.
I'll look into fixing this, as it is a bug, but its not serious in any way really.

**Comment by mjmacleod** [comment]
Just to confirm you are on 2.2.0.2, and what platform?

**Comment by cdarken** [comment]
Yes, 2.2.0.2, Arch Linux.

**Comment by mjmacleod** [comment]
Changing of address will be fixed in 2.2.0.3 build

**Comment by cdarken** [comment]
There's something else strange with v2.2.0.2. I generated a fresh wallet. I started mining on a new account. Today I found a block. But the transaction shows another address that received the reward.
This is the transaction id: e2c0e38586b0ce1035e9c1e8ab8839c3a0a80c84817fb0d5ee6397fe49f796c3
The address that's shown in the wallet interface is GeM8ENsgCgyJTzAhZf8UEYVspwdGRaasuz.
So maybe you could check if your patch fix this issue too.

**Comment by mjmacleod** [comment]
Does `validateaddress` indicate that the address belongs to your mining account?
If so its likely already fixed, just upgrade to 2.2.0.3

**Comment by cdarken** [comment]
So how would the fix work? It will use the displayed address to generate the transactions? Because I installed the new version, I rescanned the transactions and I still see `GeM8ENsgCgyJTzAhZf8UEYVspwdGRaasuz`.

**Comment by mjmacleod** [comment]
If you recover from phrase on 2.2.0.3 it will put you back in a state where the mining account only ever uses the first address in it, and the address never changes.

If you continue to use a wallet file that is already 'affected' in 2.2.0.3 then it will 'settle' on the last generated address and use that from now on, this _should_ be the same address thats shown in the UI.

You can test this by calling `getnewaddress "MyMiningAccount"` and it should return always the same address not a new one each time.

**Comment by cdarken** [comment]
Ok, thanks for the explanation.

**Comment by mjmacleod** [comment]
With 2.2.0.5 release wallet should now be 'repaired' such that you automatically land back on your original address
