### ISSUE TITLE
Mining error

### ISSUE THREAD

**Issue by timkoers** [Gulden/gulden-official#203]
### Describe the issue

A error during mining showed up.

### Can you reliably reproduce the issue?
No, I was mining when this error occured
### Expected behaviour
The mining should have not gotten any errors.

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/4262725/78344003-fcce9880-759b-11ea-9984-5bd3a0826f86.png)

### What version of Gulden are you using?
Gulden v2.2.0.4 (64-bit)

### Machine specs:
- OS: Windows 10 Pro 1909 x64
- CPU: AMD Ryzen 9 3900X 12-Core
- RAM: 32GB
- Disk size: 512GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
`debug.log` doesn't contain any information regarding this issue.

**Comment by mjmacleod** [comment]
Hello, thanks for sharing the information it has been helpful, please note that you can simply ignore this warning for now, it was just there to gather some information and is not harmful in any way, it will be removed in the next release.
