### ISSUE TITLE
Set proper user and group in .tar.gz release

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#206]
### Describe the issue
After `sudo tar xf Gulden-2.2.0.6-x86_64-linux.tar.gz` the files have a user id of 1000 and a group id of 1004. This is a small security issue.

### Can you reliably reproduce the issue?
See above

### Expected behaviour
The files in the archive should have the same id for user and group, both preferably set to root.

### Actual behaviour
See above

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Gulden are you using?
See above

### Machine specs:
n/a

**Comment by mjmacleod** [comment]
Build system now passes `--mode='u+rw,go+r-w,a+X' --owner=0 --group=0` to all tar commands for future releases.
Should you feel this is still not correct as of next release, please re-open this issue.
