### ISSUE TITLE
Witness reward in estimated earnings must be 30 Gulden instead of 20

### ISSUE THREAD

**Issue by aat58** [Gulden/gulden-official#208]
When a new witness account is made an estimated earning is presented to the customer. The calculation uses the old Witness reward of 20 Gulden instead of the new reward of 30 Gulden. So the earnings are to low calculated. 

Besides that also the calculation uses the Total_network_weight_raw instead of the eligible_network_weight or the adjusted. I know it's probably done to give a worst-case value but the eligible weight and total weight are so widely spread that the calculated earnings are 40% lower than in reality. 

### Screenshots.
https://gyazo.com/c1c64afd91babed1c17f9da86e1542f8

Gulden version 2.2.0.7

### Machine specs:
- OS: Win 10

**Comment by mjmacleod** [comment]
You are correct that it uses the raw weight, which made sense when the code was initially written but should change now.

However I'm not sure why you think it is using the old reward (20); as far as I can tell it is using 30, is there something specific that makes you think otherwise?

**Comment by aat58** [comment]
See screenshot https://gyazo.com/fd40c64318daa022518be6671a54e62c
Weight is calculated right but the estimated reward is an 0,66 smaller than in my calculations in the spreadsheet https://docs.google.com/spreadsheets/d/189vG6c3qmXYcyzPx0z9_voB7ZAeaU3Wt7v9Muf7YIT4/edit?usp=sharing (The sheet is calculating with the real time weight.)
And 20/30 = 0,66 so i imagine that the estimated earning calculation is calculating with the old reward.
