### ISSUE TITLE
Long startup time on Windows10

### ISSUE THREAD

**Issue by aat58** [Gulden/gulden-official#209]
I have detected an issue with starting up the wallet. In my experience this takes much longer than before the phase 4 update. I started an investigation and found out that several people had that experience. Then I asked if they wanted to write down the startup time and pass it on to me. with the results below:
Name:   Startup time,  system                                nr blocks behind
Aat:       7 minuten,     Windows 10 HDD 2.2.0.7,     +/- 500
Bastijn:  5 minuten,     Windows 10 2.2.0.7,             +/- 600
Bastijn:  6 minuten,     Windows 10 2.2.0.7,              +/- 1000
Bastijn:  <1minuut,     Ubuntu 2.2.0.7,                     ?
Pascal:   7 minuten,    Windows 10 2.2.0.7,               +/-600
John:    <2 minuten,   Mac book SSD 2.2.0.7,           +/-600
Jaap:     <2 minuten,   Windows 10, 2.2.0.7,             2 blocks
Harm Jan: 3 minuten, MacOS Catalina 2.2.0.7,        1100
Radis:      4" 9',            Linux Mint op mini pc,           600
Bart:       <2minuten,   Windows7,                            2500
Jeroen:    1 minuut,     Ubuntu 2.2.0.7,                        300
Jan Peter 8 minuten,   Windows 10, 2.2.0.7.              1300
Nick:        1" 55'           Windows 10 2.2.0.7,              1800 

We see that only windows10 systems suffers a slow startup but not all of them.

I started a new investigation:
I've started a new wallet. It should download the entire blockchain of course. That goes "fast" until exactly April 4th. After 35 minutes with a heavy loaded processor I have reached the point where the new phase 4 transaction format is activated. At that point the processor usage in taskmaager falls back to 3% but my hard disk usage goes to 100% and it takes over the last blocks from April 4 till 20 april more than half an hour. Tx for Tx very slowly. I see that the hard disk is glowing red but only reaches a transfer writing speed of 200-300KB/sec, that's very low. In other words, the wallet is feeding the HDD with very small pieces of data. 
Computers working with an SSD will notice it less because the standard writingspeed is much higher and apparently it only happens to people who have a windows10 machine with a HDD.

Can you reliably reproduce the issue? yes
If so, please list the steps to reproduce below:
1. startup the wallet after he is being offline for a longer period (24 hour for example)
2.
3.

Expected behaviour
Fast synchronizing within 2 minutes or faster

What version of Gulden are you using? 2.2.07
Machine specs:
- OS: windows 10 home version 1909
- CPU: i7 4710HQ
- RAM: 8Gb
- Disk size: 1Tb
- Disk Type (HD/SDD): HD

**Comment by mjmacleod** [comment]
This should be fixed as of 2.4.2 build, if it still persists after this please reopen with updated details
