### ISSUE TITLE
compile problems in ubuntu 16.04

### ISSUE THREAD

**Issue by jjj092353** [Gulden/gulden-official#21]
I gave up trying to compile on 14.04 so I brought up a new server with 16.04 and got all the updates to the OS

I downloaded source and the autogen fails as follow:

me@vps109191:/home/coins/gulden-official# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:45: installing 'build-aux/compile'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am: installing 'build-aux/depcomp'
autoreconf: automake failed with exit status: 1
me@vps109191:/home/coins/gulden-official#

**Comment by mjmacleod** [comment]
As before you need to use the 'old_autotools' branch

**Comment by jjj092353** [comment]
a question - why? I have the most recent OS available.... just wondering. - should I try to get the newest autotools?

**Comment by mjmacleod** [comment]
You have the most recent Ubuntu available.
Ubuntu is not really known/designed as a distro that people compile things on, so it tends to be rather conservative when it comes to these sorts of things, if you had the latest Arch Linux or Gentoo linux (for example) then you would have much newer autotools.

Upgrading autotools is an option, but it would probably be safer/easier to just use the "old_autotools" branch - the two branches are identical with the exception that you don't need to run "autogen" or "automake" on the "old_autotools" one.
We will continue updating both branches at every release for the foreseeable future - until we reach a point where this issue goes away, so once you are on the branch you can just stay on it.

**Comment by jjj092353** [comment]
thank you - by the way: this is an invalid link that you have on your github page:

https://github.com/Gulden/gulden-binaries/raw/master/Gulden-1.6.1.tar.gz

**Comment by jjj092353** [comment]
have you fixed this?

**Comment by mjmacleod** [comment]
Invalid link was removed thanks. We no longer upload source tarballs as the 'old_autotools' github branch replaces this.

**Comment by mjmacleod** [comment]
https://github.com/Gulden/gulden-official/tree/old_autotools

**Comment by jjj092353** [comment]
that does not work either with 16.04

I really appreciate the help you're giving me but you stuff does not work


me@vps109191:/home/coins# clear
me@vps109191:/home/coins# git clone https://github.com/Gulden/gulden-official.git
Cloning into 'gulden-official'...
remote: Counting objects: 48924, done.
remote: Total 48924 (delta 0), reused 0 (delta 0), pack-reused 48924
Receiving objects: 100% (48924/48924), 38.64 MiB | 11.63 MiB/s, done.
Resolving deltas: 100% (37288/37288), done.
Checking connectivity... done.
me@vps109191:/home/coins# cd gulden-official/
me@vps109191:/home/coins/gulden-official# ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:45: installing 'build-aux/compile'
configure.ac:45: installing 'build-aux/config.guess'
configure.ac:45: installing 'build-aux/config.sub'
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
aclocal: warning: couldn't open directory 'build-aux/m4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
me@vps109191:/home/coins/gulden-official#

**Comment by mjmacleod** [comment]
You do *not* need to run autogen. I've already told you this in a previous report.
You just run configure.

You **will** need to ensure that you have the correct boost and libdb there are **instructions** for this.

With respect if you do not have a clue what you are doing you should just use the binary, compiling things is for programmers, which quite evidently you are not, if you were you would be able to follow the simple instructions in the README.md - where it gives explicit steps for you to follow that do **not** include autogen.

>**Errors when running autogen.sh - autotool/libtool errors For older distributions with outdated autotools the above process may fail, either update to newer autotools/libtools or use the old_autotools branch, which is identical but contains a configure script that will work for old autotools. Steps:

    git checkout old_autotools
    ./configure
    make**

**Comment by jjj092353** [comment]
sorry - this is what is posted on the old_autotools page:

Gulden is autotools based, to build Gulden from this repository please follow these steps:

./autogen.sh
automake
./configure
make

**Comment by jjj092353** [comment]
I did as you suggested - configure went fine

now this:

ideas:

me@vps109191:/home/coins/gulden-official# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/coins/gulden-official/build-aux/missing aclocal-1.14 -I build-aux/m4
/home/coins/gulden-official/build-aux/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:599: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
me@vps109191:/home/coins/gulden-official#
me@vps109191:/home/coins/gulden-official#
me@vps109191:/home/coins/gulden-official# apt-get install automake
Reading package lists... Done
Building dependency tree
Reading state information... Done
automake is already the newest version (1:1.15-4ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
me@vps109191:/home/coins/gulden-official#

**Comment by mjmacleod** [comment]
Step by step Ubuntu 16.04.1 instructions tested on a clean 16.04.1 VM.
https://gist.github.com/mjmacleod/a3562af661661ce6206e5950e406ff9d

**Comment by jjj092353** [comment]
here my next problem - how do I get the account address?

me@vps109191:/usr/local/bin# LD_LIBRARY_PATH=/boost166/lib ./GuldenD getaccountaddress ""
Error: There is no RPC client functionality in GuldenD anymore. Use the Gulden-cli utility instead.
root@vps109191:/usr/local/bin# LD_LIBRARY_PATH=/boost166/lib ./Gulden-cli getaccountaddress ""
error code: -32601
error message:
Method not foundme@vps109191:/usr/local/bin# LD_LIBRARY_PATH=/boost166/lib ./Gulden-tx getaccountaddress ""
error: invalid transaction encoding
