### ISSUE TITLE
Witness account deactivated, cannot renew it, because no funding account selectable

### ISSUE THREAD

**Issue by guldenlegacy** [Gulden/gulden-official#210]
Witness account has been deactivated, but can't renew it, because I cannot select a funding account (empty).

What can I try to fix this?

![Gulden_witness_kan_niet_verniewd_worden1](https://user-images.githubusercontent.com/40773940/81698321-1948d500-9466-11ea-9827-e1b3cea36411.jpg)

### What version of Gulden are you using?
2.2.0.7

### Machine specs:
- OS: Windows 10
- CPU: i7 4770k
- RAM: 16GB
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

**Comment by mjmacleod** [comment]
Ensure you have a regular account (not mining or witness account) with a non-zero balance, restart the app and select the account from the drop down.

For queries like this you are much better off first attempting regular support channels: https://gulden.com/en#support
