### ISSUE TITLE
RPC command 'gettransaction' fails with 'JSON value is not a boolean as expected'

### ISSUE THREAD

**Issue by juggernt** [Gulden/gulden-official#212]
This issue tracker is only for technical issues related to Gulden.

The RPC command 'gettransaction "tx"' where "tx" is a wallet transaction gives error 'JSON value is not a boolean as expected'.
Gulden-cli gives the correct output.

Gulden version is 2.2.0.7

**Comment by mjmacleod** [comment]
It's not really clear what problem you are facing here exactly.
`Gulden-cli gettransaction "txid"` works for me with 2.2.0.7 just fine on any machine I test on.

1. Are you using Gulden-cli or RPC via something else?
2. On what platform
3. Using what shell
4. With what exact syntax?

**Comment by mjmacleod** [comment]
Closed due to inactivity and lack of information, pelase reopen with more information if problem persists.
