### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by andronick83** [Gulden/gulden-official#22]
novaexchange.com support:
> We can't update NLG...
> An error occurred while compilation:
> 
> nlg compilation issue - 
> ./autogen.sh 
> aclocal: couldn't open directory 'build-aux/m4': No such file or directory 
> autoreconf: aclocal failed with exit status: 1 
> 
> We don't know why it is so. It is a question to NLG dev.

**Comment by mjmacleod** [comment]
See the README.md...

Very first item in troubleshooting section applies to you.
i.e. you need to  use old_autotools branch - please read the rest of the README as well however as the rest also applies, i.e. you will need the correct boost as well as described in the README.

**Comment by andronick83** [comment]
Unfortunately Gulden compilation failed even at this time, but with another message, have tested to compile both on Novaexchanges wallet server, and on an internal developement server only for testing. Getting this:

```
Gulden/auto_checkpoints.cpp:160:9: error: ‘checkpointFile’ was not declared in this scope
         checkpointFile << hashCheckpoint.ToString();
         ^
make[2]: *** [Gulden/libgulden_common_a-auto_checkpoints.o] Error 1
make[2]: Leaving directory `/home/user/guldencoin/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/user/guldencoin/src'
make: *** [install-recursive] Error 1
```

The source was cloned for about halv an hour ago for this testing, so its the latest version... and no executable files was created when compilation stopped.

Have tested both with ./autogen.sh and without ./autogen.sh, and tested with the tip you sended to us...

The developement test server is running ubuntu server 14.04.5
