### ISSUE TITLE
How to mine Gulden on Ubuntu in CLI Mode ?

### ISSUE THREAD

**Issue by lokidaibel** [Gulden/gulden-official#241]
Hey,

how to use the Gulden Wallet to mine Gulden on a Virtual Linux Server without the need to install X
Tried the following, but it didnt success.

https://gulden.medium.com/support-the-gulden-network-by-running-your-own-full-node-48fe9edf845a

Please provide a HowTo to this. Cant find any Dokumentation on this anywhere.

**Comment by blieb** [comment]
before you can start mining you first needs to create a mining account. This can be done with `Gulden-cli createminingaccount "Mining"`

after that you can enable mining on your GuldenD.

Easiest way to do this is to add `gen=1` to your config and restart GuldenD. Then it will always start mining when GuldenD starts.


you can also use the `Gulden-cli setgenerate` command to enable/disable mining. 

```
setgenerate generate ( gen_proc_limit )

Set 'generate' true or false to turn generation on or off.
Generation is limited to 'gen_proc_limit' processors, -1 is unlimited.
Arena setup is limited to 'gen_arena_proc_limit' processors, -1 is unlimited, takes the value of 'gen_proc_limit' if not explicitely set.
See the getgenerate call for the current setting.

Arguments:
1. generate             (boolean, required) Set to true to turn on generation, off to turn off.
2. gen_proc_limit       (numeric, optional) Set the processor limit for when generation is on. Can be -1 for unlimited.
3. gen_arena_proc_limit (numeric, optional) Set the processor limit for when generation is on. Can be -1 for unlimited.
4. gen_memory_limit     (string, optional) How much system memory to use, specify a letter G/M/K/B to determine size e.g. 524288K (Kilobytes), 512M (Megabytes), 3G (Gigabytes).
5. account              (string, optional) The UUID or unique label of the account.

Examples:

Set the generation on with a limit of one processor
> Gulden-cli setgenerate true 1

Check the setting
> Gulden-cli getgenerate 

Turn off generation
> Gulden-cli setgenerate false
```

with  `Gulden-cli gethashps` you can see the current hashrate.

**Comment by mjmacleod** [comment]
Simply set up a GuldenD instance like normal and then use the following cli commmands.

1. `createminingaccount "my_account_name"`  (only need to run this once)
2. `setgenerate true num_threads num_arena_threads` (when you want to turn mining on)
3. `setgenerate false` (when you want to turn mining off
4. `gethashps` to view mining speeds
5. `getnetworkhashps` to view estimates of network mining speeds
6. `getmininginfo` for other mining info (and to check that you are using AES optimised algorithm that matches your CPU etc.)
