### ISSUE TITLE
In the good tradition of Open Source, your issues are being ignored 100%...

### ISSUE THREAD

**Issue by martinbeek** [Gulden/gulden-official#244]
The last answered issue is dating back to April 202. 
Shut down this channel if you don't use it.

**Comment by mjmacleod** [comment]
Well I'm not sure what has prompted this completely inappropriate outburst, but its certainly not true.

Perhaps you are not a developer, closed issues can be found here https://github.com/Gulden/gulden-official/issues?q=is%3Aissue+is%3Aclosed you'll note that a lot of them have actually been closed quite recently.

Kindly note that github is not the place for emotional outbursts or politics.
If you have issues tickets are always welcome.
If you have fixes pull requests are always welcome.

Threads like this on the otherhand are not welcome.
