### ISSUE TITLE
Missed header

### ISSUE THREAD

**Issue by Mezrin** [Gulden/gulden-official#28]
`auto_checkpoints.cpp` uses boost streams, but corresponding header not included.

File requires one string:
```#include <boost/filesystem/fstream.hpp>```

https://github.com/Gulden/gulden-official/blob/master/src/Gulden/auto_checkpoints.cpp#L26

I could not build application on Ubuntu without this fix

**Comment by mjmacleod** [comment]
Changed header - however note this shouldn't be necessary - if following README.md instructions it should already have been possible to build on ubuntu without this fix.
