### ISSUE TITLE
i want to move all funds from one account to another without having to wory about the fee

### ISSUE THREAD

**Issue by devlz303** [Gulden/gulden-official#34]
When I use the `move` command to move all funds from one account to another I have to subtract a tiny amount otherwise I get an error 'insufficient funds'. It would be nice to just move all funds and let the app subtract the fee for me.
Maybe it is also possible to integrate this into the UI of the Gulden application.

**Comment by mjmacleod** [comment]
Implemented in 1.6.4 release, move command can now take -1 to represent "empty this account".
