### ISSUE TITLE
Failed to sign transaction over rpc

### ISSUE THREAD

**Issue by bitbandi** [Gulden/gulden-official#38]
Signrawtransaction rpc call return this:

    "error": "Operation not valid with the current stack size"

The error is in this line: https://github.com/Gulden/gulden-official/blob/644391cc14a9e62bde0b6dcf07c7652c0a4e4757/src/rpc/rawtransaction.cpp#L757

No reason why just external keystore can sign tx, so this line sould be:

     const CKeyStore& keystore = ((fGivenKeys || !pwalletMain->activeAccount) ? tempKeystore : *(pwalletMain->activeAccount));

**Comment by mjmacleod** [comment]
Thank you for your bug report and fix, much appreciated.
Have merged this into the codebase and fix will be included in next release.
