### ISSUE TITLE
Need a way to 'defrag' the wallet

### ISSUE THREAD

**Issue by mjmacleod** [Gulden/gulden-official#4]
For vendors who receive lots of small payments, or miners, it is really annoying having to manually combine thousands of tiny transaction inputs into larger ones in order to actually be able to do something with it.

We should ideally introduce some kind of "defrag" command (possibly with the ability to set upper/lower limits of which inputs to touch) that scans through the wallet and auto-combines the various smaller inputs into larger ones in as optimal a way as possible.

Another idea which is a bit more low tech, put easier to implement as a 'consolation prize' for now would be to e.g. have a 'select 500 inputs' or similar button in coin  control.

**Comment by Redsandro** [comment]
> We should ideally introduce some kind of "defrag" command (possibly with the ability to set upper/lower limits of which inputs to touch) that scans through the wallet and auto-combines the various smaller inputs into larger ones in as optimal a way as possible.

I like this idea. With a verbose confirmation dialog, like:

> Combining 627 transactions totaling 982.16 NLG into 4 transactions will cost 4.02 NLG (fees). Continue?

**Comment by mjmacleod** [comment]
Thats basically the idea yes, there are just unfortunately much higher priorities on my development list before I can look at something like this, so for now I'm afraid the best that can be done in such a situation is to use coin control and lots of manual fiddling...

Patches are of course welcome should anyone else out there want to work on this..

**Comment by mjmacleod** [comment]
We now have a "defrag" RPC command that does this. Would be nice to integrate also into the UI in some way.
