### ISSUE TITLE
Unable to spend from BIP32 child accounts 

### ISSUE THREAD

**Issue by mjmacleod** [Gulden/gulden-official#42]
Temporary regression in codebase:

In some instances where users import an old BIP32 account (from iOS or android) they are unable to actually spend from the hidden BIP32 child account (even though the balance displays as part of the default "my account") as the UI code is under the impression that not enough coins are present.

Temporary workaround, issue following console commands to make the funds accessible again:
move "BIP32 child account" "" -1 
move "BIP32 legacychild account" "" -1 

If you get errors about your walletpassphrase first run:
walletpassphrase <yourpasswordhere> 600

**Comment by devlz303** [comment]
[transactions.json.txt](https://github.com/Gulden/gulden-official/files/1600409/transactions.json.txt)
Today I helped someone running v1.6.4.8-e1a7462 of the Gulden wallet having this issue, so probably it isn't solved completely. This person used an old IOS phrase to recover a wallet.

**Comment by devlz303** [comment]
To see if someone has these types of accounts you can ask him to execute: listaccounts

[
...,  
{
   "UUID": "4f64bb0f-23c8-43da-b16e-78589021e265",
   "label": "BIP32 legacy child account",
   "type": "HD",
   "HDindex": 2147483648
 },
  {
   "UUID": "96460116-7caf-46e2-a8c9-77aabe5af190",
   "label": "BIP32 child account",
   "type": "HD",
   "HDindex": 2147483648
 }
]

**Comment by mjmacleod** [comment]
Note that all/most wallets have these accounts by design - it's only a potential issue if they have a balance in them.

The best way to determine this is to have a user do 'listunspent' in the RPC console and then scan the output for these account names.

**Comment by mjmacleod** [comment]
Note that this is believed to be fixed in unity builds (and as of phase4 all builds) - please re-open comment if encountering this issue.
