### ISSUE TITLE
Guldend Stops with Error

### ISSUE THREAD

**Issue by mo0vjke** [Gulden/gulden-official#45]
Hi, guys. I'm trying to sync the wallet on Ubuntu 16.04.2 LTS. But after two installations and launching of guldend client I get error:

guldend: net.cpp:949: void AcceptConnection(const {anonymous}::ListenSocket&): Assertion `nMaxInbound > 0' failed.

Anyone knows, why is it happen?

**Comment by mjmacleod** [comment]
It could indicate that you have '-maxconnections' set with a too low amount, or that the program is unable to open any file descriptors for some reason (running as a user with too low permissions or read only filesystem perhaps).

Please provide more information on your setup, including your gulden.conf and debug.log for further assistance.

**Comment by mo0vjke** [comment]
Yes, it was an issue with maxconnections=8
Thank you.

**Comment by mo0vjke** [comment]
Also it was a problem, while installing the wallet in wallet.cpp file.
#include <fstream> was missed.

**Comment by mo0vjke** [comment]
#include \<fstream\>

**Comment by mjmacleod** [comment]
Okay, thanks for your report.
