### ISSUE TITLE
Using Wallet

### ISSUE THREAD

**Issue by alletro** [Gulden/gulden-official#5]
Can somebody  put some information here what to do for using the wallet for solomining.
I tried different ways like other coins, but this one looklikes different and can't get fixed.
I tried in windows and Linux but always problems with rpc login.

**Comment by mjmacleod** [comment]
Like bitcoin we have removed the 'getwork' API which most solo mining software uses - most other altcoins are on really old outdated code which is why 'getwork' still works for them.

In order to solo mine you will need to use something that supports the 'getblocktemplate' API instead of the old 'getwork' API.

**Comment by alletro** [comment]
I am not a programmer I want to mine gulden coins.
Is there somewhere a tutorial how to solo-mine gulden ?

I like the gulden and want to mine them but its for a lot impossible to do it.
I think its the same reason a lot of pools are not working and quitte with gulden.

but thanx for the explanation I hope there will be a solution for solominers in the feature.

**Comment by mjmacleod** [comment]
As of bfgminer 5.4.2 this should be possible.
You should pass the flags --no-longpoll --no-getwork  (getblocktemplates gbt must be enabled), the usual scrypt and other options that you would normally pass are also necessary.

**Comment by mjmacleod** [comment]
For anyone looking for mining support please join #mining on our slack - www.gulden.com/support - there is a thriving community there that can assist with mining queries.

**Comment by imrecsoka** [comment]
How do u mine solo using this wallet.
I can not connect, it seems to be a similar problem to Digibyte coin also.
My command line is 100% correct and my port is listening on the correct number.
Please assist me ?

**Comment by mjmacleod** [comment]
For end user support please visit https://www.reddit.com/r/GuldenCommunity/ or support.gulden.com
Github is not an appropriate place to seek end user support.
