### ISSUE TITLE
Receiving Address error

### ISSUE THREAD

**Issue by LysanderGG** [Gulden/gulden-official#52]
My receiving address dissappeared and it seems impossible to create a new one through the GUI.

File > Receiving Addresses... > New - opens a new window but I can not enter anything in the address field.
I can still receive payments on my previous address.

Here is a screenshot of the receving address.
![Imgur](http://i.imgur.com/CqUJD6L.png)

I successfully generated a new address through the console and just report the bug.

**Comment by mjmacleod** [comment]
Wallet key pool is exhausted, you simply need to unlock wallet temporarily to allow it time to replenish itself.

After next wallet release this will no longer be necessary (for HD wallets) as code will be refactored to allow address generation even when locked. (for non-HD wallets this will always be necessary but use of non-HD wallets is strongly discouraged)
