### ISSUE TITLE
Building tag v1.6.4.2 fails

### ISSUE THREAD

**Issue by dddaniel** [Gulden/gulden-official#55]
daniel@lappi:[gulden-official](v1.6.4.2):> make
Making all in src
make[1]: Entering directory '/home/daniel/srcs/gulden-official/src'
make[2]: Entering directory '/home/daniel/srcs/gulden-official/src'
  CXX      crypto/libguldenconsensus_la-aes.lo
  CXX      crypto/libguldenconsensus_la-hmac_sha256.lo
  CXX      crypto/libguldenconsensus_la-hmac_sha512.lo
  CXX      crypto/libguldenconsensus_la-ripemd160.lo
  CXX      crypto/libguldenconsensus_la-sha1.lo
  CXX      crypto/libguldenconsensus_la-sha256.lo
  CXX      crypto/libguldenconsensus_la-sha512.lo
  CXX      Gulden/Common/libguldenconsensus_la-scrypt.lo
  CXX      Gulden/Common/libguldenconsensus_la-diff_delta.lo
  CXX      Gulden/Common/libguldenconsensus_la-diff_old.lo
  CXX      Gulden/Common/libguldenconsensus_la-diff_common.lo
  CXX      Gulden/Common/hash/libguldenconsensus_la-city.lo
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:131:0: warning: "HAVE_INTTYPES_H" redefined
 #define HAVE_INTTYPES_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:8:0: note: this is the location of the previous definition
 #define HAVE_INTTYPES_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:197:0: warning: "HAVE_MEMORY_H" redefined
 #define HAVE_MEMORY_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:11:0: note: this is the location of the previous definition
 #define HAVE_MEMORY_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:215:0: warning: "HAVE_STDINT_H" redefined
 #define HAVE_STDINT_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:14:0: note: this is the location of the previous definition
 #define HAVE_STDINT_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:221:0: warning: "HAVE_STDLIB_H" redefined
 #define HAVE_STDLIB_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:17:0: note: this is the location of the previous definition
 #define HAVE_STDLIB_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:230:0: warning: "HAVE_STRING_H" redefined
 #define HAVE_STRING_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:23:0: note: this is the location of the previous definition
 #define HAVE_STRING_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:242:0: warning: "HAVE_SYS_STAT_H" redefined
 #define HAVE_SYS_STAT_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:26:0: note: this is the location of the previous definition
 #define HAVE_SYS_STAT_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:245:0: warning: "HAVE_SYS_TYPES_H" redefined
 #define HAVE_SYS_TYPES_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:29:0: note: this is the location of the previous definition
 #define HAVE_SYS_TYPES_H
 
In file included from ./compat/byteswap.h:9:0,
                 from Gulden/Common/hash/city.cpp:71:
./config/bitcoin-config.h:248:0: warning: "HAVE_UNISTD_H" redefined
 #define HAVE_UNISTD_H 1
 
In file included from Gulden/Common/hash/city.cpp:26:0:
Gulden/Common/hash/cityconfig.h:32:0: note: this is the location of the previous definition
 #define HAVE_UNISTD_H
 
  CXX      libguldenconsensus_la-arith_uint256.lo
  CXX      consensus/libguldenconsensus_la-merkle.lo
  CXX      libguldenconsensus_la-hash.lo
  CXX      primitives/libguldenconsensus_la-block.lo
  CXX      primitives/libguldenconsensus_la-transaction.lo
  CXX      libguldenconsensus_la-pubkey.lo
  CXX      script/libguldenconsensus_la-bitcoinconsensus.lo
  CXX      script/libguldenconsensus_la-interpreter.lo
  CXX      script/libguldenconsensus_la-script.lo
  CXX      script/libguldenconsensus_la-script_error.lo
  CXX      libguldenconsensus_la-uint256.lo
  CXX      libguldenconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/home/daniel/srcs/gulden-official/src/secp256k1'
make[3]: *** No rule to make target 'libsecp256k1.la'.  Stop.
make[3]: Leaving directory '/home/daniel/srcs/gulden-official/src/secp256k1'
Makefile:8728: recipe for target 'secp256k1/libsecp256k1.la' failed
make[2]: *** [secp256k1/libsecp256k1.la] Error 2
make[2]: Leaving directory '/home/daniel/srcs/gulden-official/src'
Makefile:8228: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/daniel/srcs/gulden-official/src'
Makefile:675: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by mjmacleod** [comment]
Please include as much relevant information as possible like config.log, distro and so on.
Going on the above it is most likely that something went wrong when you ran configure (missing dependency perhaps?)

**Comment by dddaniel** [comment]
./configure --with-incompatible-bdb --with-gui=qt5

[config.log.txt](https://github.com/Gulden/gulden-official/files/1182538/config.log.txt)

**Comment by dddaniel** [comment]
This maybe to root of the problem:
config.status: executing libtool commands
=== configuring in src/univalue (/home/daniel/srcs/gulden-official/src/univalue)
configure: WARNING: no configuration information is in src/univalue
=== configuring in src/secp256k1 (/home/daniel/srcs/gulden-official/src/secp256k1)
configure: WARNING: no configuration information is in src/secp256k1
Fixing libtool for -rpath problems.

**Comment by mjmacleod** [comment]
That is definitely the problem yes. Without configure running on this directories there will be no Makefile and in turn it won't be able to build them when you run make.

I have no idea though why this would be occurring on your system, a fresh checkout on several different random distros this side does not produce the same problem.

Can you possibly ensure a clean/fresh/new checkout and paste the output of "ls -l src/secp256k1/" for comparison purposes?

**Comment by dddaniel** [comment]
I already called git clean -dfx and called autreconf --install.
There was an error with the src/secp256k1/Makefile.am:

`configure.ac:9: installing 'build-aux/missing'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
`

Also CC_FOR_BUILD wasn't set.

It's building now. This is what fixed it for me:

`diff --git a/src/secp256k1/Makefile.am b/src/secp256k1/Makefile.am
index 7772a4e9..a5c4d6d8 100644
--- a/src/secp256k1/Makefile.am
+++ b/src/secp256k1/Makefile.am
@@ -75,8 +75,9 @@ TESTS = tests
 endif
 
 if USE_ECMULT_STATIC_PRECOMPUTATION
-CPPFLAGS_FOR_BUILD +=-I$(top_srcdir)
-CFLAGS_FOR_BUILD += -Wall -Wextra -Wno-unused-function
+CPPFLAGS_FOR_BUILD = -I$(top_srcdir)
+CFLAGS_FOR_BUILD = -Wall -Wextra -Wno-unused-function
+CC_FOR_BUILD = g++
 
 gen_context_OBJECTS = gen_context.o
 gen_context_BIN = gen_context$(BUILD_EXEEXT)`

**Comment by dddaniel** [comment]
There is one last undefined reference when linking:

> `  CXX      qt/qt_libguldenqt_a-qrc_bitcoin_locale.o
  CXXLD    GuldenD
libgulden_server.a(libgulden_server_a-httpserver.o): In function `InitHTTPServer()':
/home/daniel/srcs/gulden-official/src/httpserver.cpp:389: undefined reference to `event_enable_debug_logging'
/home/daniel/srcs/gulden-official/src/httpserver.cpp:387: undefined reference to `event_enable_debug_logging'
collect2: error: ld returned 1 exit status
Makefile:3529: recipe for target 'GuldenD' failed
`

**Comment by mjmacleod** [comment]
This appears to be libevent related (can't comment on your specific configuration, but definitely many people have managed to compile without this as an issue)

You might want to try manually adding -levent to the LDFlags to see if that helps, or alternatively checking which version of libevent is installed and trying a different one perhaps.

**Comment by dddaniel** [comment]
Debian testing uses libevent 2.0.5-stable, which has no event_enable_debug_logging().

httpserver.cpp even checks for version 0x02010100 which has the symbol.
On debian testing the version is 0x02010101, but without the symbol.

I have to build libevent from source then.

**Comment by mjmacleod** [comment]
I'm not entirely sure why debian testing would have a higher version but still be missing the symbol - it seems strange, but given the way debian do packaging not impossible - I don't unfortunately have time to dig right now.

I'd recommend just changing #if LIBEVENT_VERSION_NUMBER >= 0x02010100
to #if 0   instead of messing with a custom version of libevent.

As this call is definitely not necessary and the program can function fine without it..

**Comment by dddaniel** [comment]
Now it's running. I compiled the latest stable libevent myself. Thx

**Comment by mjmacleod** [comment]
The autotools part of this should be fixed now so I'm closing this issue. If anybody continues to have libevent issues or wants to dig into that please open a seperate issue.
