### ISSUE TITLE
All blocks orphan with p2pool

### ISSUE THREAD

**Issue by kr1z1s** [Gulden/gulden-official#56]
With p2pool - https://github.com/Spekske/p2pool-spek all mining blocks is orphan

Gulden LOG

`2017-08-18 01:53:45 ERROR: ProcessNewBlock: AcceptBlock FAILED
2017-08-18 01:53:45 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 5dcddaa82bc35476c51c019b5fd6113c424fc5dcd5370f6c3611df07aa011316, bad-version(0x00000002), rejected nVersion=0x00000002 block (code 17)
2017-08-18 01:53:45 ERROR: ProcessNewBlock: AcceptBlock FAILED
2017-08-18 01:53:45 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 5dcddaa82bc35476c51c019b5fd6113c424fc5dcd5370f6c3611df07aa011316, bad-version(0x00000002), rejected nVersion=0x00000002 block (code 17)
2017-08-18 01:53:45 ERROR: ProcessNewBlock: AcceptBlock FAILED
2017-08-18 01:53:45 ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 5dcddaa82bc35476c51c019b5fd6113c424fc5dcd5370f6c3611df07aa011316, bad-version(0x00000002), rejected nVersion=0x00000002 block (code 17)
2017-08-18 01:53:45 ERROR: ProcessNewBlock: AcceptBlock FAILED`

What should be changed in 

`P2P_PREFIX = 'fcfef7e0'.decode('hex') #pchmessagestart
P2P_PORT = 9231
ADDRESS_VERSION = 38 #pubkey_address
RPC_PORT = 9232
RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
            'Guldenaddress' in (yield bitcoind.rpc_help()) and
            not (yield bitcoind.rpc_getinfo())['testnet']
        ))
SUBSIDY_FUNC = lambda height: 1000*100000000 >> (height + 1)//840000
POW_FUNC = lambda data: pack.IntType(256).unpack(__import__('ltc_scrypt').getPoWHash(data))
BLOCK_PERIOD = 150 # s
SYMBOL = 'NLG'
CONF_FILE_FUNC = lambda: os.path.join(os.path.join(os.environ['APPDATA'], 'gulden') if platform.system() == 'Windows' else os.path.expanduser('~/Library/Application Support/gulden/') if platform.system() == 'Darwin' else os.path.expanduser('~/.gulden'), 'gulden.conf')
BLOCK_EXPLORER_URL_PREFIX = ''
ADDRESS_EXPLORER_URL_PREFIX = ''
TX_EXPLORER_URL_PREFIX = ''
SANE_TARGET_RANGE = (2**256//1000000000 - 1, 2**256//1000 - 1)
DUMB_SCRYPT_DIFF = 2**16
DUST_THRESHOLD = 0.03e8`

How to adapt to POW2.0?

**Comment by mjmacleod** [comment]
Stock p2pool will not work with Gulden, there are various changes required - please contact the owner of http://p2p.0x0a.nl/ perhaps he is willing to share the changes that we helped him work through with you.
Alternatively please seek support on our slack in #mining

**Comment by mjmacleod** [comment]
As per previous; I would recommend to make contact with the owner of http://p2p.0x0a.nl/ I personally assisted him with several p2pool patches that are required and his pool definitely works with them applied so if he is willing to share it would be the simplest.

**Comment by k0gen** [comment]
Hi mjmacleod

I did contacted the owner of http://p2p.0x0a.nl/ but still no response :(

Right now I'm mining fine with older version 1.6.2 but would like to upgrade to latest one and get ridge of: 
> "errors": "WARNING: Checkpoint is too old, please wait for a new checkpoint to arrive before engaging in any transactions."

**Comment by k0gen** [comment]
The code there is old ... I've tried to update the legacy getinfo rpc call references to new ones, checking the genesis block from p2pool/bitcoin/networks/gulden.py
> (yield helper.check_block_header(bitcoind, '6c5d71a461b5bff6742bb62e5be53978b8dec5103ce52d1aaab8c6a251582f92')) and
but than again I don't wan't do reinvent the wheel again.

**Comment by k0gen** [comment]
Thanks Malcolm
PS. Yes I'm on your slack and asked the question already.
