### ISSUE TITLE
operating Gulden to mac failed

### ISSUE THREAD

**Issue by marcelott** [Gulden/gulden-official#57]
Hi,

I am not technical but I have the following issue:

 i just downloaded the Gulden desktop for Mac IOS and immediately when it was downloaded the program opened with the question to fill in a portemonneewachtwoord....but....I do not have one anymore.... I just wanted to download the program and now I cannot come into the app because of this first question... but I do not have a portemonneewachtwoord anymore...

I Closed the Gulden app
I Removed the Gulden from your Applications (folder)
I opened finder and press shift-command-g (go to folder)
type ~library and click Go
now open the Application Support folder
find the Gulden folder
deleted the Gulden folder
now installed the Gulden App again I downloaded 

But still  I got the same issue.  What can I do?

**Comment by mjmacleod** [comment]
Hello, github is only for technical support.
For end user support please go to our slack https://gulden.com/support where someone can assist you.
