### ISSUE TITLE
rpc error "invalid Bitcoin address"

### ISSUE THREAD

**Issue by blieb** [Gulden/gulden-official#59]
When trying to send some Gulden to a not correct address the rpc will return error "Invalid Bitcoin address"

> Gulden-cli -testnet sendtoaddress gn8TFcCZY5SztkpxL9TQLra8gcN7Da62Zw 500000
> error code: -5
> error message:
> Invalid Bitcoin address
>

**Comment by mjmacleod** [comment]
I believe this is already fixed in 2.0 release, please confirm and reopen if not.
