### ISSUE TITLE
couldn't open directory 'build-aux/m4'

### ISSUE THREAD

**Issue by ppanther1000** [Gulden/gulden-official#6]
Cant build Guldencoin from the Github Repo on Debian7:

./autogen.sh
aclocal: couldn't open directory 'build-aux/m4': No such file or directory
autoreconf: aclocal failed with exit status: 1

The direcory build-aux/m4 exists. Any idea how to solve this?

**Comment by mjmacleod** [comment]
Hello,

Unfortunately old versions of debian do not have the correct autotools to run autogen on our codebase.
The easiest is to use a source tarball instead https://developer.gulden.com/download/155/Gulden155-linux.tar.gz.

The source tarball is pregenerated (so you can skip the autogen.sh skip entirely) just:
1) unzip
2) Run ./configure with the options you require
3) Build.

**Comment by mjmacleod** [comment]
Can you confirm if you managed to come right or not?

**Comment by ppanther1000** [comment]
Thank you for your help. I used the precompiled linux binaries.

**Comment by mjmacleod** [comment]
Okay, just shout if you need assistance in future.
