### ISSUE TITLE
Unable to determine via RPC listaccounts whether an account is actually deleted 

### ISSUE THREAD

**Issue by Qunit** [Gulden/gulden-official#61]
Currently it can only be seen in the name. When the account is deleted the name is appended with [Deleted] . However it would be better if the name stays the same and the actual state of the account is returned in a separate, dedicated field in the listaccounts response

**Comment by blieb** [comment]
Isn't it better to hide the 'deleted' accounts by listaccounts? maybe a separate rpc command to list all accounts (if someone needs it)

**Comment by mjmacleod** [comment]
It should probably take a seperate optional argument for the 'type' of accounts to list - and default to displaying only active ones.

**Comment by Qunit** [comment]
Would work for me
