### ISSUE TITLE
compile problems

### ISSUE THREAD

**Issue by jjj092353** [Gulden/gulden-official#7]
tried the repo and tarball : same errors

  CXX    libgulden_server_a-checkpoints.o
  CXX    libgulden_server_a-init.o
In file included from ./support/pagelocker.h:14:0,
                 from support/allocators/secure.h:9,
                 from key.h:10,
                 from init.cpp:17:
/usr/include/boost/thread/once.hpp: In instantiation of âvoid boost::call_once(Function, boost::once_flag&) [with Function = void (*)()]â:
./support/pagelocker.h:139:89:   required from here
/usr/include/boost/thread/once.hpp:38:18: error: no matching function for call to âcall_once(boost::once_flag&, void (*&)())â
         call_once(flag,func);
                  ^
In file included from /usr/include/boost/thread/once.hpp:20:0,
                 from ./support/pagelocker.h:14,
                 from support/allocators/secure.h:9,
                 from key.h:10,
                 from init.cpp:17:
/usr/include/boost/thread/pthread/once_atomic.hpp:121:15: note: candidate: template<class Function, class ... ArgTypes> void boost::call_once(boost::once_flag&, boost::detail::thread_move_t<T>, boost::detail::thread_move_t<Args>...)
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
               ^
/usr/include/boost/thread/pthread/once_atomic.hpp:121:15: note:   template argument deduction/substitution failed:
In file included from ./support/pagelocker.h:14:0,
                 from support/allocators/secure.h:9,
                 from key.h:10,
                 from init.cpp:17:
/usr/include/boost/thread/once.hpp:38:18: note:   mismatched types âboost::detail::thread_move_t<T>â and âvoid (*)()â
         call_once(flag,func);
                  ^
/usr/include/boost/thread/once.hpp:35:13: note: candidate: template<class Function> void boost::call_once(Function, boost::once_flag&)
 inline void call_once(Function func,once_flag& flag)
             ^
/usr/include/boost/thread/once.hpp:35:13: note:   template argument deduction/substitution failed:
/usr/include/boost/thread/once.hpp:38:18: note:   cannot convert âfuncâ (type âvoid (*)()â) to type âboost::once_flag&â
         call_once(flag,func);
                  ^
make[2]: *** [libgulden_server_a-init.o] Error 1
make[2]: Leaving directory `/home/coins/Gulden-1.5.5/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/coins/Gulden-1.5.5/src'
make: *** [all-recursive] Error 1
root@smh-us-stratum:/home/coins/Gulden-1.5.5#

**Comment by mjmacleod** [comment]
Most likely you have an incorrect version of boost or other dependency.
You should attach your entire config.log and full build log with verbose output (make V=1) if you require further assistance.

**Comment by GatekeeperZA** [comment]
Im having the same issues .. then starting GuldenD any ideas .. ?

DB_ENV->log_stat interface requires an environment configured for the logging subsystem
illegal flag combination specified to DB_ENV->open

**Comment by mjmacleod** [comment]
I've tested on ubuntu 14.04 with the problems you described on IRC and the following steps seem to get a working build for me.

 sudo apt-get update
 sudo apt-get upgrade 
 cd test
 git clone https://github.com/Gulden/gulden-official.git
 sudo apt-get update
 sudo apt-get upgrade
 sudo apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev
 sudo apt-get install libboost-all-dev
 sudo apt-get install libdb5.3 libdb5.3++ libdb5.3-dev
 cd gulden-official/
 ./autogen.sh 
 automake
 autoconf
 ./configure --with-incompatible-bdb
 make -j4
 ./src/GuldenD &
