### ISSUE TITLE
Link on Gulden.com for Linux 64 bit wrong

### ISSUE THREAD

**Issue by retrorich75** [Gulden/gulden-official#73]
A real quick one the link on the [https://gulden.com/download](http://gulden.com/download/) webpage for Linux 64 Bit points to 

https://github.com/Gulden/gulden-official/releases/download/v1.6.4.8/Gulden-1.6.4.8-x86_64.AppImage

But looking in the Github releases folder actual link is : https://github.com/Gulden/gulden-official/releases/download/v1.6.4.8/Gulden-.glibc-x86_64.AppImage

**Comment by mjmacleod** [comment]
Thank you for the report, links have been updated.
