### ISSUE TITLE
Color usage when sending funds

### ISSUE THREAD

**Issue by simondel** [Gulden/gulden-official#74]
Today I sent some Gulden for the first time and my first reaction was *'Oh god something went wrong'* when I looked at the transactions. 

The overview of the transactions shows a green or red circle in front of the transaction. I read this as the status of the transaction, with green meaning that the transaction was succesfully processed. I believe this circle is grey when it's unconfirmed.

I understand that you want to show added funds in green and removed funds in red, but you already have that at the end. It would make more sense to me if the last transaction in this screenshot had a green circle.
![afbeelding](https://user-images.githubusercontent.com/4221997/34872461-2e0b5608-f791-11e7-95d8-fb870bfe1e74.png)

**Comment by mjmacleod** [comment]
Completely new Android wallet is now out, so this issue is likely no longer relevant.
