### ISSUE TITLE
Autoconf fails to use correct path for QtWebKit and QtWebKitWidgets

### ISSUE THREAD

**Issue by tuaris** [Gulden/gulden-official#76]
On my system, the autoconf script falsely identifies the QtWebKit and QtWebKitWidgets include directories as

```
-I/usr/local/include/qt5/Qt5WebKit -I/usr/local/include/qt5/Qt5WebKitWidgets
```
Where in fact, they should be

```
-I/usr/local/include/qt5/QtWebKit -I/usr/local/include/qt5/QtWebKitWidgets
```

To work around this I had to manually pass the following

```
CXXFLAGS+=	-I${QT_INCDIR}/QtWebKit -I${QT_INCDIR}/QtWebKitWidgets
```

I think the problem might be somewhere in this file around this line.  Or it may need additional detection code specifically for those two libraries.

https://github.com/Gulden/gulden-official/blob/master/build-aux/m4/bitcoin_qt.m4#L392

**Comment by mjmacleod** [comment]
Please attach config.log for failed configuration attempt.

**Comment by mjmacleod** [comment]
No longer relevant as webkit has been dropped as a dependency.
