### ISSUE TITLE
Transaction too large

### ISSUE THREAD

**Issue by Redsandro** [Gulden/gulden-official#8]
I have never actually send a transaction. This is my first attempt.

![image](https://cloud.githubusercontent.com/assets/1702193/18582652/6ea26f74-7c06-11e6-9014-d66298810ac3.png)

What does it mean? I'm trying to send a relatively small amount.

![image](https://cloud.githubusercontent.com/assets/1702193/18582691/9be46b7c-7c06-11e6-9132-c94ae2fe0b0e.png)

`Gulden version v1.5.5.0-911f59f-dirty (64-bit)` on Linux Mint 18 (AKA Ubuntu 16.04)

**Comment by Redsandro** [comment]
I think it's because I've accumulated small transactions using http://kwartjeterug.nl/ and faucets, and now I can't use this balance to make any serious kind of transaction.

1. Is there a way to combine everything in an automated fashion that doesn't require me to be to be a computer expert?
1. Can I choose a received transaction that is bigger than the send amount to base the transaction on?
1. Can I manually choose multiple received transactions to base the send transaction on?

**Comment by mjmacleod** [comment]
You can use coin control features (enabled in settings > options) to control which inputs are used when creating a payment.

**Comment by mjmacleod** [comment]
Duplicate of #4
