### ISSUE TITLE
Win32/x64 Wallet - Application can be 'hidden' by accident (maximised but not visible)

### ISSUE THREAD

**Issue by EyePeaSea** [Gulden/gulden-official#81]
**Platform:** x64 and Win32 - v1.6.4.8

**Description:** When the application closes, it stores the current window location and size (nWindowPos and nWindowsize under HKCU).  If the screen size changes after the app is closed (e.g. disconnect a second monitor from a PC or laptop), then the application doesn't verify the new screen size when it starts up. This can result in the application opening "off screen".  It's fiddly (but possible) to get the application back onto the main screen, and this will baffle some users.

**Source of error:** Failure to verify stored window size/location is valid on current screen size during startup.

**Full Fix:** If stored window location puts the application off the screen, then reset the window location to ensure that the application starts up 'mid-screen' and also update the registry values..

**Comment by EyePeaSea** [comment]
Pseudo code suggestion to resolve issue:

guiutil.cpp
-----------

Modify conditional line to:

   ` if ( !pos.x() && !pos.y() ) **|| pos.x > size.width || pos.y > size.height)** {`

So if pos.x / pos.y value are not defined OR pos.x OR pos.y are invalid, then set window position/size to default values.

**Comment by EyePeaSea** [comment]
Ignore the ** - formatting error.

**Comment by FornaxNLG** [comment]
We have seen this one come up in supportquestions.
Untill fixed in the code the user can take these steps:
- Singleclick the Guldenwallet-button on the taskbar
- Press Alt-Space and in the pop-up select 'Maximise'
- Drag the now fullscreen Guldenwallet down by the titlebar to restore original size.

**Comment by mjmacleod** [comment]
I believe this is possibly already fixed in the 2.0 codebase, so I'm going to tentatively close this bug for now. If it ends up not being fixed please reopen and we will address it in the first post 2.0 release.
