### ISSUE TITLE
Android app tells the IBAN transaction limit is 10.000 euro

### ISSUE THREAD

**Issue by blieb** [Gulden/gulden-official#82]
The android app tells user that is is 10.000 euro per transaction. The real limit is 1000 euro.

![screen shot 2018-01-19 at 11 30 53](https://user-images.githubusercontent.com/540248/35146755-41ad0d0c-fd0c-11e7-81bf-85f8efbc91ed.png)

**Comment by mjmacleod** [comment]
This is due to some confusion in the nocks API - https://www.nocks.com/api/settings that the android app pulls the data from.
Nocks have confirmed they will update the API on their side.
