### ISSUE TITLE
iOS app tells the IBAN transaction limit is 500 euro

### ISSUE THREAD

**Issue by blieb** [Gulden/gulden-official#83]
During transaction to iban, it is not possible to make payments over 500 euro. The real limit by nocks is 1000 euro.

![img_2079](https://user-images.githubusercontent.com/540248/35146904-dd0bd0a8-fd0c-11e7-93e0-85f2ee1adb02.jpg)

**Comment by mjmacleod** [comment]
Make sure iOS pulls the latest limit data from https://www.nocks.com/api/settings - like the other two apps.
