### ISSUE TITLE
readonly account getnewaddress readonly side not accepted by master

### ISSUE THREAD

**Issue by blieb** [Gulden/gulden-official#84]
I've connected a server via readonly account to a account in my desktop wallet. Only the addresses generated by server are not readable by desktop:

example:
```
martin@guldennode1:~$ Gulden-cli getnewaddress 6a866602-a6fb-4441-86de-0d73a85a403d
GZ8v28PLFsXHEzHbhaVbp9iFMB6s4uKMyr

martin@guldennode1:~$ Gulden-cli validateaddress GZ8v28PLFsXHEzHbhaVbp9iFMB6s4uKMyr
{
  "isvalid": true,
  "address": "GZ8v28PLFsXHEzHbhaVbp9iFMB6s4uKMyr",
  "scriptPubKey": "76a914a7c0a0896b52dadb35ddc9fa47c745db9527543288ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "pubkey": "02b7d55f874c8c4d3ebeefb4c897588620aa027c45f365c29a4da2520644ea643d",
  "iscompressed": true,
  "account": "6a866602-a6fb-4441-86de-0d73a85a403d",
  "accountlabel": "server"
}
```

![screen shot 2018-01-28 at 22 52 57](https://user-images.githubusercontent.com/540248/35487635-2d02a5aa-047e-11e8-9feb-82c9d8af9d90.png)

address generated by desktop: GabJ9LTAijrUYodoAWhQBCcYjQRwkLu69W

```
martin@guldennode1:~$ Gulden-cli validateaddress GabJ9LTAijrUYodoAWhQBCcYjQRwkLu69W
{
  "isvalid": true,
  "address": "GabJ9LTAijrUYodoAWhQBCcYjQRwkLu69W",
  "scriptPubKey": "76a914b7b6094b29097c0cf2519d7beb8acb722a4c194088ac",
  "ismine": true,
  "iswatchonly": false,
  "isscript": false,
  "pubkey": "027f1571d63f2d7615046534eda3690a1bbd1d95f7ba5c16777a0c901ec9d26ad1",
  "iscompressed": true,
  "account": "6a866602-a6fb-4441-86de-0d73a85a403d",
  "accountlabel": "server"
}
```

**Comment by mjmacleod** [comment]
Issue appears to be to do with large "gaps" in the address chains, with the server generating lots of unused addresses.
As the desktop wallet only generates keypool=n addresses ahead it doesn't know that addreses >n ahead have been used by the server.


This can be worked around by using a sufficiently large -keypool=n value (possibly in the thousands) and/or by attempting to avoid having a large quantity of unused addresses generated on the server side.

There are some improvements that should be made also to our HD code as our current "address gap" handling is sub-optimal.
