### ISSUE TITLE
Desktop App - 1.6.4.10 - QR Code cropped

### ISSUE THREAD

**Issue by EyePeaSea** [Gulden/gulden-official#86]
The receiving address QR code picture frame adjusts its size based on the size of the main wallet window.  On lower resolutions screens, the default size of the App means that the bottom of the QR code is cropped, and so will not scan properly. See example screen shot:

![qr code error](https://user-images.githubusercontent.com/35574121/35907308-6f4e176e-0be5-11e8-97e9-9c9bf54f4b2b.PNG)

**Comment by mjmacleod** [comment]
Note this is only with the initial sync message showing, which will hide either simply by pressing hide or when the blockchain is fully synced, so is at best a very minor inconvenience.

**Comment by EyePeaSea** [comment]
Thanks - just checked that.  All ok now that the wallet is sync'd.  So, very, very minor issue.

**Comment by mjmacleod** [comment]
I believe this might be fixed in latest app (sync window is a bit shorter now) - please reopen if still an issue.
