### ISSUE TITLE
Certain fonts, table details and checkboxes too small on Lubuntu 17.10

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#88]
Certain fonts, table details and checkboxes are too small on Lubuntu 17.10. they are hardly readable or usable. Please fix this. See screenshots below.

The same goes for the options menu where the normal fonts are too large and checkboxes and other texts are also too small.

![2018-03-04-134059_1920x1080_scrot](https://user-images.githubusercontent.com/198964/36945757-e8c3dbb6-1fb2-11e8-8616-6058beaf9be6.png)

![2018-03-04-134057_1920x1080_scrot](https://user-images.githubusercontent.com/198964/36945758-e8e007aa-1fb2-11e8-9825-3a868f44e3c3.png)

![2018-03-04-134053_1920x1080_scrot](https://user-images.githubusercontent.com/198964/36945759-e8fcc368-1fb2-11e8-9689-f48b4850b930.png)

![2018-03-04-134051_1920x1080_scrot](https://user-images.githubusercontent.com/198964/36945760-e9197184-1fb2-11e8-97ff-af0122bbb728.png)

![2018-03-04-134049_1920x1080_scrot](https://user-images.githubusercontent.com/198964/36945761-e93b2518-1fb2-11e8-95c8-2f81d1239141.png)

**Comment by mjmacleod** [comment]
Are you running from the .AppImage or have you compiled yourself?

**Comment by PanderMusubi** [comment]
$ ./Gulden-1.6.4.10-x86_64.AppImage

**Comment by PanderMusubi** [comment]
On another computer (desktop) with the same version of Lubuntu and the same screen dimensions, this problem does not occur. The machine for which the problem was reported is a laptop. Both have no special configuration.

**Comment by mjmacleod** [comment]
Thanks for the additional information, could you check the resolution and DPI settings on both machines, perhaps this might help narrow down the issue.

**Comment by PanderMusubi** [comment]
Both have the same output for DPI:

    $ xdpyinfo|grep dots
      resolution:    96x96 dots per inch

but slightly different for resolution, desktop:

    $ xrandr |grep '*'
       1920x1080     60.00*+  50.00    59.94

laptop (where problem is):

    $ xrandr |grep '*'
       1920x1080     60.00*+  59.93    40.00

**Comment by mjmacleod** [comment]
What are the monitor specs for the laptop? Wondering if it is HiDPI (retina). I'll see if I can reproduce on a rettina machine when I get a chance.

**Comment by PanderMusubi** [comment]
No retina, it is a

    13.3" 16:9 HD+ (1600x900)/IPS FHD (1920x1080)

**Comment by mbootsman** [comment]
Same issue here. Using ubuntu 18.04

```
$ xrandr | grep '*'
3780x2160     60.00*+  30.00  
```

```
$ xdpyinfo|grep dots
resolution:    96x96 dots per inch
```

**Comment by mjmacleod** [comment]
Can you confirm window manager/version and supply any other potential machine specific information.
Model of machine (if laptop).
Monitor brand/model if desktop.
Graphics card.

Or anything else you think might be relevant. I'd love to fix this issue but without some way to reproduce it is a bit tricky. I can't reproduce it on any copies of ubuntu locally and I've tried several different versions across different machines.

**Comment by mbootsman** [comment]
```
$ wmctrl -m
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

```
$ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/560] (rev cf)
```
Added screenshot with Gulden website behind the Gulden App.
![201807 5-screenshot-1605](https://user-images.githubusercontent.com/5878082/42327907-408729e6-806d-11e8-81a1-625ea7732bce.png)

**Comment by mjmacleod** [comment]
Can any of the affected parties please confirm if the latest build (2.0.0.10) changes this in any way?

**Comment by PanderMusubi** [comment]
Yes, better in 2.0.0, also little bit better in version 1.6.4. So is probably a mix of newer libraries and some changes being made to Gulden.

![2018-08-09-113715_1920x1080_scrot](https://user-images.githubusercontent.com/198964/43891088-cbb1c0be-9bc8-11e8-9f85-31f1dab6a554.png)

Must say that the normal/default font is too small related to the other better-desgned texts.

**Comment by mbootsman** [comment]
No changes here.

**Comment by mjmacleod** [comment]
General clean-up of all stale ux related issues, as we are soon moving to a new electron based UI. If issue is urgent and/or still reproduces reopen w ith further info.
