### ISSUE TITLE
Problem during install

### ISSUE THREAD

**Issue by RomHtK** [Gulden/gulden-official#89]
Hi, I'm trying to reinstall the Gulden wallet.
I have a problem because during this phase:

sudo mkdir /boost166 && sudo chmod -R a+rwx /boost166 && wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0. tar.bz2 && tar -xvf boost_1_61_0. tar. bz2 && cd boost_1_61_0/ &&&. /bootstrap. sh &&&&. /b2 --prefix=/boost166 cxxflags=-fPIC cflags=-fPIC link=static installation

I had an internet disconnection. Now when I want to repeat this command he gives me: 
mkdir: impossible to create the directory "/boost166": The file exists

But impossible to find it, because I would like to try to delete it and start again.
Could you help me?

**Comment by mjmacleod** [comment]
Do not recommend compiling unless you actually need to do so; only programmers and technical users should need this.

For regular users it's best to just install the AppImage https://github.com/Gulden/gulden-official/releases - for end user support visit https://gulden.com/support

**Comment by mjmacleod** [comment]
If you do insist on compiling though you simply need to delete the directory to start again i.e.:
rm -rf /boost166

**Comment by RomHtK** [comment]
Perfect! 
Thank you very much for your answer, 
I thought compilation was the only method. 
I'm going to delete the folder in question and will probably use the appimage file
