### ISSUE TITLE
Update licenses

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#90]
Please, add LICENSE files to:
* https://github.com/Gulden/gulden-seeder
* https://github.com/Gulden/gulden-raspbian-repository
* https://github.com/Gulden/guldensign

Change the end year to 2018 for:
* https://github.com/Gulden/gulden-official/blob/master/COPYING_gulden
* https://dev.gulden.com/license/

Split license into upstream and gulden for:
* https://github.com/Gulden/coinomi-android/blob/master/COPYING
* https://github.com/Gulden/gulden-seeder

**Comment by mjmacleod** [comment]
Licensing for gulden-official is updated for latest branches.
Licensing has been added for guldensign and gulden-raspbian-repository.
Coinomi-android was a temporary branch to push a single change upstream so I've simply archived it instead.

gulden-seeder cannot specify a license until upstream clarify their position https://github.com/sipa/bitcoin-seeder/issues/20 but I will update it as soon as they do.

I've notified the website maintainer to update the website license.
